services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeMe
      MONGO_INITDB_DATABASE: app
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
