export const NFZ_CONSOLE_SERVICE_PATHS = {
  services: 'nfz/services',
  schemas: 'nfz/schemas',
  manifest: 'nfz/manifest',
  builder: 'nfz/builder',
  status: 'nfz/status',
  rbac: 'nfz/rbac',
  presets: 'nfz/presets',
  init: 'nfz/init',
} as const

export const NFZ_AUTH_EVENT_TYPES = [
  'ensure-start',
  'ensure-finish',
  'session-sync',
  'sso-session-sync',
  'feathers-session-sync',
  'authenticate',
  'reauth-skipped',
  'reauth-success',
  'reauth-failure',
  'logout',
  'keycloak-client-session',
  'keycloak-bridge-success',
  'keycloak-bridge-fallback',
  'keycloak-bearer-validated',
  'keycloak-bearer-missing',
  'protected-page-ready',
  'protected-page-blocked',
] as const

export type NfzAuthEventType = (typeof NFZ_AUTH_EVENT_TYPES)[number]

export const NFZ_MODULE_CAPABILITIES = {
  architecture: {
    apiModel: 'feathers-first',
    nitroRole: [
      'host the embedded Feathers runtime',
      'provide Nuxt and H3 infrastructure integration',
      'keep optional deprecated compatibility facades only',
    ],
  },
  modes: ['embedded', 'remote'],
  transports: ['rest', 'socketio'],
  restFrameworks: ['express', 'koa'],
  schemaModes: ['none', 'zod', 'json'],
  serviceKinds: ['adapter', 'custom', 'file', 'remote'],
  adapters: ['memory', 'mongodb'],
  authProviders: ['jwt', 'local', 'oauth', 'oidc', 'api-key', 'custom', 'keycloak-bridge', 'remote', 'none'],
  consoleServices: [
    { key: 'services', path: NFZ_CONSOLE_SERVICE_PATHS.services, methods: ['find'], purpose: 'service discovery' },
    { key: 'schemas', path: NFZ_CONSOLE_SERVICE_PATHS.schemas, methods: ['find', 'get', 'patch'], purpose: 'schema inspection and synchronization' },
    { key: 'manifest', path: NFZ_CONSOLE_SERVICE_PATHS.manifest, methods: ['get', 'patch'], purpose: 'NFZ manifest access' },
    { key: 'builder', path: NFZ_CONSOLE_SERVICE_PATHS.builder, methods: ['create'], purpose: 'preview and apply builder plans' },
    { key: 'status', path: NFZ_CONSOLE_SERVICE_PATHS.status, methods: ['find'], purpose: 'console and auth status' },
    { key: 'rbac', path: NFZ_CONSOLE_SERVICE_PATHS.rbac, methods: ['get', 'patch'], purpose: 'RBAC policy management' },
    { key: 'presets', path: NFZ_CONSOLE_SERVICE_PATHS.presets, methods: ['find', 'create'], purpose: 'builder preset preview and apply' },
    { key: 'init', path: NFZ_CONSOLE_SERVICE_PATHS.init, methods: ['create'], purpose: 'guided initialization operations' },
  ],
  composables: [
    'useFeathers',
    'useService',
    'useRawService',
    'useAuth',
    'useAuthRuntime',
    'useAuthDiagnostics',
    'useAuthTrace',
    'useAuthBoundFetch',
    'useAuthBoundFetchImplementation',
    'useAuthenticatedRequest',
    'useProtectedPage',
    'useProtectedService',
    'useProtectedTool',
    'useBuilderClient',
    'useMongoManagementClient',
    'useNfzAdminClient',
    'useKeycloakBridge',
    'useNfzPinia',
  ],
  clientHelpers: ['hasNfzPinia'],
  serverHooks: ['authenticateNfz'],
  serverLifecycle: [
    'infrastructure',
    'modules:pre',
    'plugins',
    'services',
    'modules:post',
    'app.setup',
    'routers',
    'ready',
    'teardown',
  ],
  authEvents: NFZ_AUTH_EVENT_TYPES,
} as const

export type NfzModuleCapabilities = typeof NFZ_MODULE_CAPABILITIES
