import type { ResolvedOptions } from '../../options'
import type { DefaultAuthOptions } from '../../options/authentication'
import type { RestOptions } from '../../options/transports/rest'
import type { WebsocketOptions } from '../../options/transports/websocket'

import { put, puts } from '../utils'

export function getServerAppContents(options: ResolvedOptions) {
  return async (): Promise<string> => {
    const transports = options?.transports
    const rest = Boolean(transports?.rest)
    const framework = (transports?.rest as RestOptions)?.framework
    const exp = framework === 'express'
    const koa = framework === 'koa'
    const sio = Boolean(transports?.websocket)

    const authStrategies = (options?.auth as DefaultAuthOptions)?.authStrategies
    const auth = (authStrategies || []).length > 0
    const mongo = Boolean(options.database?.mongo)

    const websocketOptions = (transports?.websocket as WebsocketOptions) || undefined
    const websocketPath = JSON.stringify(websocketOptions?.path ?? '/socket.io')
    const websocketConnectTimeout = websocketOptions?.connectTimeout != null
      ? `    connectTimeout: ${String(websocketOptions.connectTimeout)},\n`
      : ''
    const websocketTransports = websocketOptions?.transports?.length
      ? `    transports: ${JSON.stringify(websocketOptions.transports)},\n`
      : ''
    const websocketCors = websocketOptions?.cors
      ? `    cors: ${JSON.stringify(websocketOptions.cors)},\n`
      : ''

    return `// ! Generated by nuxt-feathers-zod - do not change manually
${put(options.loadFeathersConfig, `import configuration from '@feathersjs/configuration'`)}
import { attachNitroApp, configureNfzInfrastructure } from 'nuxt-feathers-zod/server-app-utils'
import { feathers } from '@feathersjs/feathers'
${puts([
  [koa, `import { koa as feathersKoa, rest } from '@feathersjs/koa'`],
  [exp, `import feathersExpress, { rest, json, urlencoded } from '@feathersjs/express'`],
  [sio, `import socketio from '@feathersjs/socketio'`],
])}
${put(koa, `import { koaErrorHandler } from '@gabortorma/feathers-nitro-adapter/handlers'`)}
${put(auth, `import authentication from './authentication'`)}
${put(mongo, `import mongodb from './mongodb'`)}

export async function createFeathersApp(nitroApp, config) {
  const app = ${puts([
    [koa, `feathersKoa(feathers())`],
    [exp, `feathersExpress(feathers())`],
    [!rest, `feathers()`],
  ])}

  attachNitroApp(app, nitroApp)

${put(options.loadFeathersConfig, `  app.configure(configuration())
`)}${put(rest, `  // REST framework setup
  ${put(koa, `app.configure(koaErrorHandler)
`)}  ${put(exp, `// Parse JSON/urlencoded request bodies before Feathers REST routes.
  // This is required for embedded REST auth and all POST/PATCH/PUT requests.
  app.use(json())
  app.use(urlencoded({ extended: true }))
  console.info('[NFZ server] body parser pre-rest=true')

  // Express error handler is configured later (after services)
`)}  app.set('framework', '${framework}')
  app.configure(rest(${put(auth, `{
    authentication: {
      strategies: ['${authStrategies?.join(`', '`)}'],
    },
  }`)}))
`)}
${put(sio, `  // Socket.io transport
  app.set('websocket', true)
  app.configure(socketio({
    path: ${websocketPath},
${websocketConnectTimeout}${websocketTransports}${websocketCors}  }))
`)}
  return app
}

export async function configureFeathersInfrastructure(app, config) {
  await configureNfzInfrastructure(app, config, {
    authentication: ${auth ? 'authentication' : 'undefined'},
    mongodb: ${mongo ? 'mongodb' : 'undefined'},
  })
}
`
  }
}
