import type { ResolvedOptions } from '../../options'
import type { DefaultAuthOptions } from '../../options/authentication'
import type { RestOptions } from '../../options/transports/rest'
import type { WebsocketOptions } from '../../options/transports/websocket'
import { put, puts } from '../utils'

export function getServerAppContents(options: ResolvedOptions) {
  return async (): Promise<string> => {
    const transports = options?.transports
    const rest = !!transports?.rest
    const framework = (transports?.rest as RestOptions)?.framework
    const exp = framework === 'express'
    const koa = framework === 'koa'
    const sio = !!transports?.websocket

    const authStrategies = (options?.auth as DefaultAuthOptions)?.authStrategies
    const auth = (authStrategies || []).length > 0
    const mongo = !!options.database?.mongo

    const restPath = (transports?.rest as RestOptions)?.path
    const websocketOptions = (transports?.websocket as WebsocketOptions) || undefined
    const websocketPath = JSON.stringify(websocketOptions?.path ?? '/socket.io')
    const websocketConnectTimeout = websocketOptions?.connectTimeout != null
      ? `    connectTimeout: ${String(websocketOptions.connectTimeout)},\n`
      : ''
    const websocketTransports = websocketOptions?.transports?.length
      ? `    transports: ${JSON.stringify(websocketOptions.transports)},\n`
      : ''
    const websocketCors = websocketOptions?.cors
      ? `    cors: ${JSON.stringify(websocketOptions.cors)},\n`
      : ''

    // NOTE: this file is executed in Nitro runtime. Avoid TS-only syntax in the generated output.
    return `// ! Generated by nuxt-feathers-zod - do not change manually
${put(options.loadFeathersConfig, `import configuration from '@feathersjs/configuration'`)}
import { feathers } from '@feathersjs/feathers'
${puts([
  [koa, `import { koa as feathersKoa, rest } from '@feathersjs/koa'`],
  [exp, `import feathersExpress, { rest } from '@feathersjs/express'`],
  [sio, `import socketio from '@feathersjs/socketio'`],
])}
${put(rest, `import { ${framework}ErrorHandler } from '@gabortorma/feathers-nitro-adapter/handlers'`)}
${put(auth, `import authentication from './authentication'`)}
${put(mongo, `import mongodb from './mongodb'`)}

export async function createFeathersApp(nitroApp, config) {
  const app = ${puts([
    [koa, `feathersKoa(feathers())`],
    [exp, `feathersExpress(feathers())`],
    [!rest, `feathers()`],
  ])}

  // Attach nitroApp for downstream modules
  app.nitroApp = nitroApp

${put(options.loadFeathersConfig, `  app.configure(configuration())
`)}
${put(rest, `  // REST framework setup
  ${put(koa, `app.configure(koaErrorHandler)
`)}
  ${put(exp, `// Express error handler is configured later (after services)
`)}
  app.set('framework', '${framework}')
  app.configure(rest(${put(auth, `{
    authentication: {
      strategies: ['${authStrategies?.join(`', '`)}'],
    },
  }`)}))
`)}

${put(sio, `  // Socket.io transport
  app.set('websocket', true)
  app.configure(socketio({
    path: ${websocketPath},
${websocketConnectTimeout}${websocketTransports}${websocketCors}  }))
`)}

  return app
}

export async function configureFeathersInfrastructure(app, config) {
  const mongoConfig = config?.database?.mongo
  const mongoEnabled = !!(mongoConfig && mongoConfig.enabled && mongoConfig.url)

  if (mongoEnabled) {
    app.set('mongodb', mongoConfig.url)
    app.set('mongoPath', mongoConfig.management?.basePath || '/mongo')
  }

${put(auth, `  if (config?.auth?.enabled !== false)
    await app.configure(authentication)

`)}${put(mongo, `  if (mongoEnabled)
    await mongodb(app)
`)} }
`
  }
}
