import type { ResolvedOptions } from '../../options'

export function getServerAuthTypesContents(options: ResolvedOptions) {
  const path = options.auth && options.auth.authenticationService
    ? options.auth.authenticationService.replace(/^\/+/, '')
    : 'authentication'

  return (): string => `// ! Generated by nuxt-feathers-zod - do not change manually
import type { NfzAuthenticationService } from 'nuxt-feathers-zod/server-auth'

declare module './server' {
  interface ServiceTypes {
    '${path}': NfzAuthenticationService
  }
}
`
}
