import type { ResolvedOptions } from '../../options'

export function getServerAuthContents(_options: ResolvedOptions) {
  return (): string => `// ! Generated by nuxt-feathers-zod - do not change manually
import { useRuntimeConfig } from '#imports'
import { configureNfzAuthentication } from 'nuxt-feathers-zod/server-auth'
import { defineFeathersServerPlugin } from './server'

export default defineFeathersServerPlugin(async (app) => {
  const authOptions = useRuntimeConfig()._feathers.auth
  if (!authOptions)
    return

  await configureNfzAuthentication(app, authOptions)
})
`
}
