import type { ResolvedOptions } from '../../options'

export function getServerAuthDtsContents(_options: ResolvedOptions) {
  return (): string => {
    return `// ! Generated by nuxt-feathers-zod - do not change manually
import type { AuthenticationService } from '@feathersjs/authentication'

declare module './server' {
  interface ServiceTypes {
    authentication: AuthenticationService
  }
}
`
  }
}
