import type { ResolvedOptions } from '../../options'

export function getServerAuthTypesContents(_options: ResolvedOptions) {
  return (): string => `// ! Generated by nuxt-feathers-zod - do not change manually
import type { AuthenticationService } from '@feathersjs/authentication'

declare module './server' {
  interface ServiceTypes {
    authentication: AuthenticationService
  }
}
`
}
