import type { ResolvedOptions } from '../../options'
import type { DefaultAuthOptions } from '../../options/authentication'
import { put, puts } from '../utils'

export function getServerAuthContents(options: ResolvedOptions) {
  return (): string => {
    const authStrategies = (options.auth as DefaultAuthOptions).authStrategies
    const jwt = authStrategies.includes('jwt')
    const local = authStrategies.includes('local')
    const oauth = authStrategies.includes('oauth')

    return `// ! Generated by nuxt-feathers-zod - do not change manually
import { useRuntimeConfig } from '#imports'
import { defineFeathersServerPlugin } from './server'
import { AuthenticationService ${put(jwt, `, JWTStrategy `)}} from '@feathersjs/authentication'
${put(local, `import { LocalStrategy } from '@feathersjs/authentication-local'`)}
${put(oauth, `import { oauth } from '@feathersjs/authentication-oauth'`)}

export default defineFeathersServerPlugin((app) => {
  const authOptions = useRuntimeConfig()._feathers.auth

  // Feathers AuthenticationService reads its configuration from app.get(configKey).
  // The documented dynamic setup is app.set('authentication', config) followed by
  // new AuthenticationService(app, 'authentication'). Passing the config object as a
  // third constructor argument is not part of the Feathers API.
  if (authOptions && typeof authOptions === 'object')
    app.set('authentication', authOptions)

  const authentication = new AuthenticationService(app, 'authentication')

${puts([
  [jwt, `  authentication.register('jwt', new JWTStrategy())`],
  [local, `  authentication.register('local', new LocalStrategy())`],
])}

  app.use('authentication', authentication)

${put(oauth, `  app.configure(oauth())\n\n`)}  // Compatibility: allow Keycloak SSO (and other providers) to post tokens using alternative field names.
  // Feathers JWTStrategy expects 'accessToken', while many IdPs expose 'access_token'.
  app.service('authentication').hooks({
    before: {
      create: [
        async (context) => {
          const d = context.data
          if (d && typeof d === 'object') {
            // access_token -> accessToken
            if (d.access_token && !d.accessToken)
              d.accessToken = d.access_token
            // jwt -> accessToken (some clients send jwt)
            if (d.jwt && !d.accessToken)
              d.accessToken = d.jwt
            // token/bearer -> accessToken
            if (d.token && !d.accessToken)
              d.accessToken = d.token
            if (d.bearer && !d.accessToken)
              d.accessToken = d.bearer
            // normalize keycloak user hints for downstream hooks/strategies
            if (d.keycloakUser && !d.user)
              d.user = d.keycloakUser
            if (d.user && !d.keycloakUser)
              d.keycloakUser = d.user
          }
          return context
        },
      ],
    },
  })
})
`
  }
}
