import type { ResolvedOptions } from '../../options'

export function getServerDatabaseContents(_options: ResolvedOptions) {
  return (): string => `// ! Generated by nuxt-feathers-zod - do not change manually
// Named database registry for the embedded runtime. Credentials remain in private runtimeConfig.

import { createDatabaseInfrastructure } from 'nuxt-feathers-zod/server-database'

export const database = createDatabaseInfrastructure()

export default database
`
}

export function getServerDatabaseTypesContents(_options: ResolvedOptions) {
  return () => `// ! Generated by nuxt-feathers-zod - do not change manually

import type { NfzDatabaseRegistry } from 'nuxt-feathers-zod/server-database'

declare module './server' {
  interface Configuration {
    databaseRegistry?: NfzDatabaseRegistry
    databaseConnections?: NfzDatabaseRegistry['connections']
    database_ok?: boolean
    knexClient?: any
    mongodb?: string
    mongoPath?: string
    mongodbClient?: Promise<any>
    mongodbDb?: any
    mongodbConnection?: any
    currentDatabase?: string
    mongodb_ok?: boolean
  }
}
`
}
