import type { ResolvedOptions } from '../../../runtime/options'

export function getServerKeycloakContents(options: ResolvedOptions) {
  return async () => {
    return `// ! Generated by nuxt-feathers-zod - do not change manually
import { createRemoteJWKSet, jwtVerify } from 'jose'


function getBearer(headers) {
  const auth = headers?.authorization || headers?.Authorization
  if (!auth || typeof auth !== 'string') return null
  if (!auth.startsWith('Bearer ')) return null
  return auth.slice(7)
}

async function safeResolveUser(app, cfg, payload) {
  const sub = payload?.sub
  if (!sub) return payload

  try {
    const users = app.service(cfg.userService)
    const found = await users.find({ query: { [cfg.serviceIdField]: sub }, paginate: false })
    const first = Array.isArray(found) ? found[0] : (found?.data?.[0] ?? null)
    if (first) return first

    // Minimal create data to avoid schema conflicts
    const created = await users.create({ [cfg.serviceIdField]: sub })
    return created
  }
  catch (e) {
    // Fallback: no DB user service or schema mismatch -> return token payload as user
    return { [cfg.serviceIdField]: sub, ...payload }
  }
}

export function keycloakAuthorizationHook(app, cfg) {
  const issuer = \`\${cfg.serverUrl}/realms/\${cfg.realm}\`
  const jwks = createRemoteJWKSet(new URL(\`\${issuer}/protocol/openid-connect/certs\`))

  return async (context) => {
    // Only external calls
    if (!context.params?.provider) return context

    const token = getBearer(context.params.headers)
    if (!token) return context

    const { payload } = await jwtVerify(token, jwks, {
      issuer,
      audience: cfg.clientId,
    })

    context.params.client = payload
    context.params.user = await safeResolveUser(app, cfg, payload)
    context.params.permissions = []

    return context
  }
}

export function keycloakBridgeService(app, cfg) {
  return {
    async create(data) {
      const fakeCtx = {
        app,
        params: { headers: { Authorization: \`Bearer \${data.access_token}\` }, provider: 'rest' },
      }

      await keycloakAuthorizationHook(app, cfg)(fakeCtx)

      return {
        user: fakeCtx.params.user,
        permissions: fakeCtx.params.permissions,
      }
    },

    async patch(_, data) {
      return this.create(data)
    },

    async remove() {
      return { ok: true }
    },
  }
}
`
  }
}
