import type { ResolvedOptions } from '../../../runtime/options'

export function getServerKeycloakDtsContents(_options: ResolvedOptions) {
  return async () => {
    return `// ! Generated by nuxt-feathers-zod - do not change manually
import type { Application, HookContext } from '@feathersjs/feathers'

export type KeycloakConfig = {
  serverUrl: string
  realm: string
  clientId: string
  secret?: string
  userService: string
  serviceIdField: string
  authServicePath: string
  permissions?: boolean
}

export function keycloakAuthorizationHook(
  app: Application,
  cfg: KeycloakConfig,
): (context: HookContext) => Promise<HookContext>

export function keycloakBridgeService(
  app: Application,
  cfg: KeycloakConfig,
): {
  create(data: { access_token: string }): Promise<{ user: any, permissions: any[] }>
  patch(id: any, data: { access_token: string }): Promise<{ user: any, permissions: any[] }>
  remove(): Promise<{ ok: boolean }>
}
`
  }
}
