import type { ResolvedOptions } from '../../../runtime/options'

export function getServerKeycloakContents(_options: ResolvedOptions) {
  return async () => {
    return `// ! Generated by nuxt-feathers-zod - do not change manually
import { createRemoteJWKSet, jwtVerify } from 'jose'

function getBearer(headers) {
  const auth = headers?.authorization || headers?.Authorization
  if (!auth || typeof auth !== 'string') return null
  if (!auth.startsWith('Bearer ')) return null
  return auth.slice(7)
}

async function safeResolveUser(app, cfg, payload, hintedUser) {
  const sub = payload?.sub
  if (!sub) return hintedUser || payload

  try {
    const users = app.service(cfg.userService)
    const found = await users.find({ query: { [cfg.serviceIdField]: sub }, paginate: false })
    const first = Array.isArray(found) ? found[0] : (found?.data?.[0] ?? null)
    if (first) return { ...hintedUser, ...payload, ...first }

    const created = await users.create({
      [cfg.serviceIdField]: sub,
      ...(hintedUser && typeof hintedUser === 'object' ? hintedUser : {}),
      preferred_username: hintedUser?.preferred_username || payload?.preferred_username || hintedUser?.email || payload?.email,
      email: hintedUser?.email || payload?.email,
    })
    return created
  }
  catch (_e) {
    return { [cfg.serviceIdField]: sub, ...(hintedUser && typeof hintedUser === 'object' ? hintedUser : {}), ...payload }
  }
}

export function keycloakAuthorizationHook(app, cfg) {
  const issuer = cfg.serverUrl + '/realms/' + cfg.realm
  const jwks = createRemoteJWKSet(new URL(issuer + '/protocol/openid-connect/certs'))

  return async (context) => {
    if (!context.params?.provider) return context

    const token = getBearer(context.params?.headers)
    if (!token) return context

    const verified = await jwtVerify(token, jwks, {
      issuer,
      audience: cfg.clientId,
    })

    const payload = verified.payload
    context.params.client = payload
    context.params.user = await safeResolveUser(app, cfg, payload)
    context.params.permissions = []

    return context
  }
}

export function keycloakBridgeService(app, cfg) {
  return {
    async create(data) {
      const token = data?.access_token || data?.accessToken || data?.jwt || data?.token
      const hintedUser = data?.keycloakUser || data?.user || data?.tokenParsed || null
      const fakeCtx = {
        app,
        params: { headers: { Authorization: token ? 'Bearer ' + token : '' }, provider: 'rest' },
      }

      await keycloakAuthorizationHook(app, cfg)(fakeCtx)

      if (!fakeCtx.params.user && hintedUser)
        fakeCtx.params.user = hintedUser

      return {
        user: fakeCtx.params.user,
        permissions: fakeCtx.params.permissions,
        accessToken: token || null,
        authentication: token ? { strategy: 'keycloak', accessToken: token } : undefined,
        keycloakUser: hintedUser || fakeCtx.params.client || null,
        bridge: {
          strategy: token ? 'keycloak' : null,
          validated: Boolean(fakeCtx.params.user || hintedUser),
          userService: cfg.userService,
          serviceIdField: cfg.serviceIdField,
          authServicePath: cfg.authServicePath,
        },
      }
    },

    async patch(_id, data) {
      return this.create(data)
    },

    async remove() {
      return { ok: true }
    },
  }
}
`
  }
}

export function getServerKeycloakTypesContents(_options: ResolvedOptions) {
  return () => `// ! Generated by nuxt-feathers-zod - do not change manually
import type { HookContext, Application } from './server'

export interface KeycloakConfig {
  serverUrl: string
  realm: string
  clientId: string
  secret?: string
  userService: string
  serviceIdField: string
  authServicePath: string
  permissions?: boolean
}

export declare function keycloakAuthorizationHook(app: Application, cfg: KeycloakConfig): (context: HookContext) => Promise<HookContext>
export declare function keycloakBridgeService(app: Application, cfg: KeycloakConfig): {
  create(data: { access_token?: string, accessToken?: string, jwt?: string, token?: string, user?: any, keycloakUser?: any, tokenParsed?: any }): Promise<{ user: any, permissions: any[], accessToken?: string, authentication?: { strategy: string, accessToken: string }, bridge?: { strategy: string | null, validated: boolean, userService: string, serviceIdField: string, authServicePath: string } }>
  patch(id: any, data: { access_token?: string, accessToken?: string, jwt?: string, token?: string, user?: any, keycloakUser?: any, tokenParsed?: any }): Promise<{ user: any, permissions: any[], accessToken?: string, authentication?: { strategy: string, accessToken: string }, bridge?: { strategy: string | null, validated: boolean, userService: string, serviceIdField: string, authServicePath: string } }>
  remove(): Promise<{ ok: boolean }>
}
`
}
