import type { MongoClientOptions } from 'mongodb'
import type { ResolvedOptions } from '../../options'
import type { ResolvedMongoManagementOptions, ResolvedMongoOptions } from '../../options/database/mongodb'
import { klona } from 'klona/json'

export function getServerMongodbContents(options: ResolvedOptions) {
  return (): string => {
    const mongoUrl = options?.database?.mongo?.url
    const mongoOptions = klona(options?.database?.mongo) as Partial<ResolvedMongoOptions>
    const management = (mongoOptions.management || {}) as Partial<ResolvedMongoManagementOptions>
    delete mongoOptions.url
    delete mongoOptions.management

    const mongoClientOptions = mongoOptions as MongoClientOptions

    return `// ! Generated by nuxt-feathers-zod - do not change manually
// MongoDB infrastructure for embedded runtime (Feathers Dove style)

import { authenticate } from '@feathersjs/authentication'
import { MongoClient } from 'mongodb'
import {
  aggregate,
  collections,
  count,
  database,
  documents,
  indexes,
  requireMongoAdmin,
  schema,
  stats,
  users,
} from 'feathers-mongodb-management-ts'
const mongodbConnection = ${JSON.stringify(mongoUrl)}
const mongodbOptions = ${JSON.stringify(mongoClientOptions, null, 2)}
const management = ${JSON.stringify(management, null, 2)}

function ensureLeadingSlash(value) {
  const input = String(value || '').trim()
  if (!input)
    return '/'
  return input.startsWith('/') ? input : '/' + input
}

function stripEdgeSlashes(value) {
  let result = String(value || '')
  while (result.startsWith('/')) result = result.slice(1)
  while (result.endsWith('/')) result = result.slice(0, -1)
  return result
}

function normalizePath() {
  const parts = Array.from(arguments)
  const normalized = parts
    .filter(part => part != null && String(part).trim() !== '')
    .map(part => stripEdgeSlashes(String(part)))
    .filter(Boolean)
    .join('/')

  return normalized ? '/' + normalized : '/'
}

function hasService(app, path) {
  const normalized = String(path || '').replace(/^\\//, '')
  return Object.prototype.hasOwnProperty.call(app.services || {}, normalized)
}

function resolveMongoAdminUser(params) {
  const userProperty = management.auth?.userProperty || 'user'
  return params?.[userProperty]
}

function normalizeAuthStrategies(value) {
  if (!Array.isArray(value))
    return ['jwt']

  const strategies = value
    .map(item => String(item || '').trim())
    .filter(Boolean)

  return strategies.length ? strategies : ['jwt']
}

function createMongoAdminBeforeHooks(authOptions) {
  if (!authOptions)
    return []

  const hooks = []

  if (authOptions.authenticate !== false) {
    const strategies = normalizeAuthStrategies(authOptions.authStrategies)
    hooks.push(authenticate(...strategies))
  }

  hooks.push(requireMongoAdmin(authOptions))
  return hooks
}

function createAuditLogger() {
  if (!management.audit?.enabled)
    return undefined

  return {
    enabled: true,
    logger(entry) {
      console.info('[NFZ mongo-admin]', JSON.stringify(entry))
    },
    resolveUser(params) {
      const user = resolveMongoAdminUser(params)
      return user?.email || user?.userId || user?._id || user?.id || undefined
    }
  }
}

function createAuthOptions() {
  if (!management.auth?.enabled)
    return undefined

  return {
    authenticate: management.auth.authenticate !== false,
    authStrategies: normalizeAuthStrategies(management.auth.authStrategies),
    userProperty: management.auth.userProperty || 'user',
    adminField: management.auth.adminField || 'isAdmin',
    adminRoleNames: Array.isArray(management.auth.adminRoleNames) && management.auth.adminRoleNames.length ? management.auth.adminRoleNames : ['admin'],
    rolesField: management.auth.rolesField || 'roles',
    permissionsField: management.auth.permissionsField || 'permissions',
    requiredPermissions: Array.isArray(management.auth.requiredPermissions) ? management.auth.requiredPermissions : [],
    requiredScopes: Array.isArray(management.auth.requiredScopes) ? management.auth.requiredScopes : [],
    scopeField: management.auth.scopeField || 'scope',
  }
}

function inferDatabaseName(connection) {
  try {
    const parsed = new URL(connection)
    const pathname = String(parsed.pathname || '').replace(/^\\//, '')
    return pathname || 'test'
  }
  catch {
    return 'test'
  }
}

export async function mongodb(app) {
  const connection = app.get('mongodb') || mongodbConnection
  const defaultMongoPath = ensureLeadingSlash(management.basePath || '/mongo')
  const configuredMongoPath = app.get('mongoPath')
  const mongoPath = ensureLeadingSlash(configuredMongoPath || defaultMongoPath)

  if (!configuredMongoPath)
    app.set('mongoPath', mongoPath)

  if (!connection || typeof connection !== 'string') {
    throw new Error('Missing MongoDB connection string in app.get("mongodb")')
  }

  const client = await MongoClient.connect(connection, mongodbOptions)
  const databaseName = inferDatabaseName(connection)
  const db = client.db(databaseName)

  app.set('mongodbClient', Promise.resolve(db))
  app.set('mongodbDb', db)
  app.set('mongodbConnection', client)
  app.set('currentDatabase', databaseName)
  app.set('mongodb_ok', true)

  if (!management.enabled)
    return

  const baseOptions = {
    db,
    whitelistDatabases: Array.isArray(management.whitelistDatabases) && management.whitelistDatabases.length ? management.whitelistDatabases : undefined,
    blacklistDatabases: Array.isArray(management.blacklistDatabases) && management.blacklistDatabases.length
      ? management.blacklistDatabases
      : management.showSystemDatabases === true
        ? undefined
        : ['admin', 'config', 'local'],
    whitelistCollections: Array.isArray(management.whitelistCollections) && management.whitelistCollections.length ? management.whitelistCollections : undefined,
    blacklistCollections: Array.isArray(management.blacklistCollections) && management.blacklistCollections.length ? management.blacklistCollections : ['system.profile'],
    allowCreateDatabase: management.allowCreateDatabase === true,
    allowDropDatabase: management.allowDropDatabase === true,
    allowCreateCollection: management.allowCreateCollection === true,
    allowDropCollection: management.allowDropCollection === true,
    allowInsertDocuments: management.allowInsertDocuments === true,
    allowPatchDocuments: management.allowPatchDocuments === true,
    allowReplaceDocuments: management.allowReplaceDocuments === true,
    allowRemoveDocuments: management.allowRemoveDocuments === true,
    audit: createAuditLogger(),
    auth: createAuthOptions(),
  }

  const mount = (path, factory, specificOptions = {}) => {
    if (hasService(app, path))
      return

    const serviceOptions = { ...baseOptions, ...specificOptions, serviceName: path }
    app.configure(factory(serviceOptions))

    const beforeAllHooks = createMongoAdminBeforeHooks(serviceOptions.auth)
    if (beforeAllHooks.length > 0) {
      try {
        app.service(path).hooks({ before: { all: beforeAllHooks } })
      }
      catch {
        // ignore late service adapters
      }
    }
  }

  if (management.exposeDatabasesService) {
    mount(normalizePath(mongoPath, 'databases'), database)
  }

  if (management.exposeCollectionsService) {
    mount(normalizePath(mongoPath, ':db', 'collections'), collections)
  }

  if (management.exposeUsersService) {
    mount(normalizePath(mongoPath, 'users'), users, { hasUserInfosCommand: true })
  }

  if (management.exposeCollectionCrud) {
    mount(normalizePath(mongoPath, ':db', 'stats'), stats)
    mount(normalizePath(mongoPath, ':db', ':collection', 'indexes'), indexes)
    mount(normalizePath(mongoPath, ':db', ':collection', 'count'), count)
    mount(normalizePath(mongoPath, ':db', ':collection', 'schema'), schema, { sampleSize: 50 })
    mount(normalizePath(mongoPath, ':db', ':collection', 'documents'), documents)
    mount(normalizePath(mongoPath, ':db', ':collection', 'aggregate'), aggregate, {
      maxPipelineStages: 20,
      maxResultSize: 100,
    })
  }
}

export default mongodb
`
  }
}

export function getServerMongodbTypesContents(_options: ResolvedOptions) {
  return () => `// ! Generated by nuxt-feathers-zod - do not change manually
import type { Application } from './declarations'

export declare function mongodb(app: Application): Promise<void>
export default mongodb
`
}
