import type { MongoClientOptions } from 'mongodb'
import type { ResolvedOptions } from '../../options'
import type { ResolvedMongoManagementOptions, ResolvedMongoOptions } from '../../options/database/mongodb'
import { klona } from 'klona/json'

export function getServerMongodbContents(options: ResolvedOptions) {
  return (): string => {
    const mongoUrl = options?.database?.mongo?.url
    const mongoOptions = klona(options?.database?.mongo) as Partial<ResolvedMongoOptions>
    const management = (mongoOptions.management || {}) as Partial<ResolvedMongoManagementOptions>
    delete mongoOptions.url
    delete mongoOptions.management

    const mongoClientOptions = mongoOptions as MongoClientOptions
    const authEnabled = !!options.auth
    const authImport = authEnabled
      ? 'import { authenticate } from \'@feathersjs/authentication\'\n'
      : ''

    const authHookBody = authEnabled
      ? [
          '  if (!management.auth)',
          '    return',
          '  app.service(path).hooks({',
          '    around: { all: [authenticate(\'jwt\')] },',
          '    before: { all: [] },',
          '    after: { all: [] },',
          '    error: { all: [] },',
          '  })',
        ].join('\n')
      : '  return'

    return `// ! Generated by nuxt-feathers-zod - do not change manually
// MongoDB infrastructure for embedded runtime (Feathers Dove style)

import { MongoClient } from 'mongodb'
import {
  aggregate,
  collections,
  count,
  database,
  documents,
  indexes,
  schema,
  stats,
  users,
} from 'feathers-mongodb-management-ts'
${authImport}import { defineFeathersServerPlugin } from './server.js'

const mongodbConnection = ${JSON.stringify(mongoUrl)}
const mongodbOptions = ${JSON.stringify(mongoClientOptions, null, 2)}
const management = ${JSON.stringify(management, null, 2)}

function stripEdgeSlashes(value) {
  let result = value
  while (result.startsWith('/')) result = result.slice(1)
  while (result.endsWith('/')) result = result.slice(0, -1)
  return result
}

function normalizePath(...parts) {
  const normalized = parts
    .filter(part => part != null && String(part).trim() !== '')
    .map(part => stripEdgeSlashes(String(part)))
    .filter(Boolean)
    .join('/')

  return normalized ? "/\${normalized}" : '/'
}

function hasService(app, path) {
  const normalized = String(path || '').replace(/^\\//, '')
  return Object.prototype.hasOwnProperty.call(app.services || {}, normalized)
}

function applyJwtAuthHook(app, path) {
${authHookBody}
}

export const mongodb = defineFeathersServerPlugin(async (app) => {
  const connection = app.get('mongodb') || mongodbConnection
  const mongoPath = app.get('mongoPath') || management.basePath || '/mongo'

  if (!connection || typeof connection !== 'string') {
    throw new Error('Missing MongoDB connection string in app.get("mongodb")')
  }

  const client = await MongoClient.connect(connection, mongodbOptions)
  const databaseName = new URL(connection).pathname.replace(/^\\//, '') || 'test'
  const db = client.db(databaseName)

  app.set('mongodbClient', Promise.resolve(db))
  app.set('mongodbDb', db)
  app.set('mongodbConnection', client)
  app.set('currentDatabase', databaseName)
  app.set('mongodb_ok', true)

  if (!management.enabled)
    return

  const access = {
    whitelistDatabases: ['admin', 'config', databaseName],
    blacklistCollections: ['system.profile'],
  }

  if (management.exposeDatabasesService) {
    const path = normalizePath(mongoPath, 'databases')
    if (!hasService(app, path)) {
      app.configure(database({ db, serviceName: path, ...access }))
      applyJwtAuthHook(app, path)
    }
  }

  if (management.exposeCollectionsService) {
    const path = normalizePath(mongoPath, ':db', 'collections')
    if (!hasService(app, path)) {
      app.configure(collections({ db, serviceName: path, ...access }))
      applyJwtAuthHook(app, path)
    }
  }

  if (management.exposeUsersService) {
    const path = normalizePath(mongoPath, 'users')
    if (!hasService(app, path)) {
      app.configure(users({ db, serviceName: path }))
      applyJwtAuthHook(app, path)
    }
  }

  if (management.exposeCollectionCrud) {
    const statsPath = normalizePath(mongoPath, ':db', 'stats')
    if (!hasService(app, statsPath)) {
      app.configure(stats({ db, serviceName: statsPath, ...access }))
      applyJwtAuthHook(app, statsPath)
    }

    const indexesPath = normalizePath(mongoPath, ':db', ':collection', 'indexes')
    if (!hasService(app, indexesPath)) {
      app.configure(indexes({ db, serviceName: indexesPath, ...access }))
      applyJwtAuthHook(app, indexesPath)
    }

    const countPath = normalizePath(mongoPath, ':db', ':collection', 'count')
    if (!hasService(app, countPath)) {
      app.configure(count({ db, serviceName: countPath, ...access }))
      applyJwtAuthHook(app, countPath)
    }

    const schemaPath = normalizePath(mongoPath, ':db', ':collection', 'schema')
    if (!hasService(app, schemaPath)) {
      app.configure(schema({ db, serviceName: schemaPath, sampleSize: 50, ...access }))
      applyJwtAuthHook(app, schemaPath)
    }

    const documentsPath = normalizePath(mongoPath, ':db', ':collection', 'documents')
    if (!hasService(app, documentsPath)) {
      app.configure(documents({ db, serviceName: documentsPath, ...access }))
      applyJwtAuthHook(app, documentsPath)
    }

    const aggregatePath = normalizePath(mongoPath, ':db', ':collection', 'aggregate')
    if (!hasService(app, aggregatePath)) {
      app.configure(aggregate({
        db,
        serviceName: aggregatePath,
        maxPipelineStages: 20,
        maxResultSize: 100,
        ...access,
      }))
      applyJwtAuthHook(app, aggregatePath)
    }
  }
})

export default mongodb
`
  }
}
