import type { Import } from 'unimport'
import type { ResolvedOptions } from '../../options'
import type { DefaultAuthOptions } from '../../options/authentication'
import type { ServicesDirs } from '../../options/services'
import type { RestOptions } from '../../options/transports/rest'
import type { WebsocketOptions } from '../../options/transports/websocket'
import { scanDirExports } from 'unimport'
import { filterExports, setImportsMeta } from '../../options/utils'
import { put, puts } from '../utils'

async function getServices(servicesDirs: ServicesDirs): Promise<Import[]> {
  const services = await scanDirExports(servicesDirs, {
    filePatterns: ['**/*.ts'],
    types: false,
  })
  return services
    .filter(({ from }) => !/\w+\.\w+\.ts$/.test(from)) // / !path.matchesGlob(from, '**/*.*.ts'), // path.matchesGlob is experimental
    .filter(filterExports)
}

export function getServerPluginContents(options: ResolvedOptions) {
  return async (): Promise<string> => {
    const services = setImportsMeta(await getServices(options.servicesDirs))

    const plugins = options.server.plugins

    const modules = [...services, ...plugins]

    const transports = options?.transports
    const rest = !!transports?.rest
    const framework = (transports?.rest as RestOptions)?.framework
    const exp = framework === 'express'
    const koa = framework === 'koa'
    const sio = !!transports?.websocket
    const routers = [exp && 'createExpressRouter', koa && 'createKoaRouter', sio && 'createSocketIoRouter'].filter(Boolean)
    const mongo = !!options.database?.mongo
    const authStrategies = (options?.auth as DefaultAuthOptions)?.authStrategies
    const auth = (authStrategies || []).length > 0
    const authService = (options?.auth as DefaultAuthOptions)?.service
    const restPath = (transports?.rest as RestOptions)?.path
    const websocketPath = (transports?.websocket as WebsocketOptions)?.path

    const swaggerEnabled = !!options.swagger
    const swagger = options.swagger as any
    // Swagger (legacy) is a middleware route (/docs, /docs.json), not a Feathers service.
    // It must be registered *after* REST/websocket/auth init, but *before* services, so it can
    // collect per-service `docs:` metadata and avoid 404s caused by trailing slash normalization.
    const normalizePath = (p: string) => {
      if (!p)
        return ''
      return p.startsWith('/') ? p : `/${p}`
    }

    const trimTrailingSlash = (p: string) => {
      if (!p)
        return ''
      return p.length > 1 && p.endsWith('/') ? p.slice(0, -1) : p
    }

    const rawDocsPath = typeof swagger?.docsPath === 'string' ? swagger.docsPath : '/docs'
    const docsPath = trimTrailingSlash(normalizePath(rawDocsPath))
    const docsPathSlash = `${docsPath}/`
    const rawDocsJsonPath = typeof swagger?.docsJsonPath === 'string' ? swagger.docsJsonPath : '/docs.json'
    const docsJsonPath = trimTrailingSlash(normalizePath(rawDocsJsonPath))

    const swaggerInitBlock = swaggerEnabled
      ? `  // Init Swagger (feathers-swagger legacy)
  

  app.configure(swagger.customMethodsHandler)
  app.configure(swagger({
    docsPath: '${docsPath}',
    docsJsonPath: '/swagger.json',
    specs: {
      info: ${JSON.stringify(swagger?.info ?? { title: 'API Docs', description: 'Feathers API', version: '1.0.0' })},
      components: {
        securitySchemes: {
          BearerAuth: {
            type: 'http',
            scheme: 'bearer',
            bearerFormat: 'JWT',
          },
        },
      },
      security: [
        { BearerAuth: [] },
      ],
    },
    ui: swagger.swaggerUI({ docsPath: '${docsPath}' }),
  }))
`
      : ''

    return `// ! Generated by nuxt-feathers-zod - do not change manually
import type { NitroApp } from 'nitropack'
import type { Application } from './server'
${put(options.loadFeathersConfig, `import configuration from '@feathersjs/configuration'`)}
import { feathers } from '@feathersjs/feathers'
${puts([
  [koa, `import { bodyParser, koa as feathersKoa, rest } from '@feathersjs/koa'`],
  [exp, `import feathersExpress, { json, rest, urlencoded } from '@feathersjs/express'`],
  [sio, `import socketio from '@feathersjs/socketio'`],
])}
${put(swaggerEnabled, `import swagger from 'feathers-swagger'`)}
${put(rest, `import { ${framework}ErrorHandler } from '@gabortorma/feathers-nitro-adapter/handlers'`)}
${put(auth, `import authentication from './authentication'`)}
import { ${routers.join(', ')} } from '@gabortorma/feathers-nitro-adapter/routers'
import { defineNitroPlugin } from 'nitropack/dist/runtime/plugin'
${put(mongo, `import mongodb from './mongodb'`)}
${modules.map(module => module.meta.import).join('\n')}

export default defineNitroPlugin((nitroApp: NitroApp) => {
  const app: Application = ${puts([
    [koa, `feathersKoa(feathers())`],
    [exp, `feathersExpress(feathers())`],
    [!rest, `feathers()`],
  ])}
${put(options.loadFeathersConfig, `
  app.configure(configuration())
`)}
${put(swaggerEnabled, swaggerInitBlock)}
  // Add nitroApp to feathers app
  app.nitroApp = nitroApp;
${put(rest, `${put(koa, `
  // Set up Koa middleware
  app.configure(koaErrorHandler)
  app.use(bodyParser())`)}
${put(exp, `  // Set up Express middleware
  app.use(json())
  app.use(urlencoded({ extended: true }))
`)}
  ${put(rest, `// Init rest server
  app.set('framework', '${framework}')
  app.configure(rest(${put(auth, `{
    authentication: {
      strategies: ['${authStrategies?.join(`', '`)}'],
    },
  }`)}))  
`)}`)}

  // Init socket.io server for real-time functionality
  app.set('websocket', ${!!sio})${put(sio, `
  app.configure(socketio({ 
    path: '${websocketPath}',
    transports: ['websocket']
  }))`)}  

  ${put(auth, `// Init auth
  app.configure(authentication)
`)}
  ${put(mongo, `// Init mongodb
  app.configure(mongodb)
`)}

  // Init services
  ${services.map(service => `app.configure(${service.meta.importId})`).join('\n  ')}

  // Init plugins
  ${plugins.map(plugin => `app.configure(${plugin.meta.importId})`).join('\n  ')}

${put(exp, `
  // Set up Express middleware for 404s and the error handler
  app.configure(expressErrorHandler)
`)}
  void app.setup().then(()=> { // TODO: make async in Nitro v3
${puts([
  [koa, `    // Init koa router\n    createKoaRouter(app, '${restPath}')`],
  [exp, `    // Init express router\n    createExpressRouter(app, '${restPath}')`],
  [sio, `    // Init socket.io router\n    createSocketIoRouter(app)`],
])}        
  }); 

  nitroApp.hooks.hook("close", async () => app.teardown());  
})
`
  }
}
