import type { Import } from 'unimport'
import type { ResolvedOptions } from '../../options'
import type { DefaultAuthOptions } from '../../options/authentication'
import type { ServicesDirs } from '../../options/services'
import type { RestOptions } from '../../options/transports/rest'
import type { WebsocketOptions } from '../../options/transports/websocket'
import { scanDirExports } from 'unimport'
import { filterExports, setImportsMeta } from '../../options/utils'
import { put, puts } from '../utils'

async function getServices(servicesDirs: ServicesDirs): Promise<Import[]> {
  const services = await scanDirExports(servicesDirs, {
    filePatterns: ['**/*.ts'],
    types: false,
  })
  return services
    .filter(({ from }) => !/\w+\.\w+\.ts$/.test(from))
    .filter(filterExports)
}

export function getServerPluginContents(options: ResolvedOptions) {
  return async (): Promise<string> => {
    const services = setImportsMeta(await getServices(options.servicesDirs))

    const plugins = options.server.plugins
    const serverModules = options.server.modules

    const modules = [...services, ...plugins, ...serverModules]

    const transports = options?.transports
    const rest = !!transports?.rest
    const framework = (transports?.rest as RestOptions)?.framework
    const exp = framework === 'express'
    const koa = framework === 'koa'
    const sio = !!transports?.websocket

    const routers = [exp && 'createExpressRouter', koa && 'createKoaRouter', sio && 'createSocketIoRouter'].filter(Boolean)

    const mongo = !!options.database?.mongo

    const authStrategies = (options?.auth as DefaultAuthOptions)?.authStrategies
    const auth = (authStrategies || []).length > 0

    // keycloak
    const keycloakEnabled = !!options.keycloak
    const keycloak = options.keycloak as any

    const restPath = (transports?.rest as RestOptions)?.path
    const websocketOptions = (transports?.websocket as WebsocketOptions) || undefined
    const websocketPath = websocketOptions?.path

    const swaggerEnabled = !!options.swagger
    const swagger = options.swagger as any

    const normalizePath = (p: string) => {
      if (!p)
        return ''
      return p.startsWith('/') ? p : `/${p}`
    }

    const trimTrailingSlash = (p: string) => {
      if (!p)
        return ''
      return p.length > 1 && p.endsWith('/') ? p.slice(0, -1) : p
    }

    const docsPath = trimTrailingSlash(normalizePath(swagger?.docsPath ?? '/docs'))
    const docsJsonPath = trimTrailingSlash(normalizePath(swagger?.docsJsonPath ?? '/docs.json'))

    const swaggerInitBlock = swaggerEnabled
      ? `  // Init Swagger (feathers-swagger legacy)
  app.configure(swagger.customMethodsHandler)
  app.configure(swagger({
    docsPath: '${docsPath}',
    docsJsonPath: '${docsJsonPath}',
    specs: {
      info: ${JSON.stringify(swagger?.info ?? { title: 'API Docs', description: 'Feathers API', version: '1.0.0' })},
      components: {
        securitySchemes: {
          BearerAuth: {
            type: 'http',
            scheme: 'bearer',
            bearerFormat: 'JWT',
          },
        },
      },
      security: [
        { BearerAuth: [] },
      ],
    },
    ui: swagger.swaggerUI({ docsPath: '${docsPath}' }),
  }))
`
      : ''

    const keycloakInitBlock = keycloakEnabled
      ? `  // Init Keycloak-only SSO (global hook + bridge service)
  const keycloakConfig = ${JSON.stringify({
    serverUrl: keycloak.serverUrl,
    realm: keycloak.realm,
    clientId: keycloak.clientId,
    issuer: keycloak.issuer || `${keycloak.serverUrl.replace(/\/$/, '')}/realms/${keycloak.realm}`,
    audience: keycloak.audience || keycloak.clientId,
    secret: keycloak.secret,
    userService: keycloak.userService || 'users',
    serviceIdField: keycloak.serviceIdField || 'keycloakId',
    authServicePath: keycloak.authServicePath || '/_keycloak',
    permissions: !!keycloak.permissions,
  })}
  app.hooks({ before: [keycloakAuthorizationHook(app, keycloakConfig)] })
  app.use(keycloakConfig.authServicePath, keycloakBridgeService(app, keycloakConfig) as any)
`
      : ''

    // IMPORTANT: Nitro may load this file through a Rollup pipeline that does *not* transpile TypeScript.
    // Keep the generated plugin free of TS-only syntax.
    return `// ! Generated by nuxt-feathers-zod - do not change manually
${put(keycloakEnabled, `import { keycloakAuthorizationHook, keycloakBridgeService } from './keycloak'`)}
import { createFeathersApp } from './app'
${put(swaggerEnabled, `import swagger from 'feathers-swagger'`)}
${put(rest, `import { ${framework}ErrorHandler } from '@gabortorma/feathers-nitro-adapter/handlers'`)}
${put(auth, `import authentication from './authentication'`)}
import { ${routers.join(', ')} } from '@gabortorma/feathers-nitro-adapter/routers'
import { defineNitroPlugin } from 'nitropack/dist/runtime/plugin'
${put(mongo, `import mongodb from './mongodb'`)}
${modules.map(module => module.meta.import).join('\n')}

export default defineNitroPlugin(async (nitroApp) => {
  const config = {
    transports: {
      rest: ${rest ? JSON.stringify({ enabled: true, framework, path: restPath }) : 'false'},
      websocket: ${sio ? JSON.stringify({ enabled: true, ...(websocketOptions || {}), path: websocketPath ?? '/socket.io' }) : 'false'},
    },
    loadFeathersConfig: ${options.loadFeathersConfig ? 'true' : 'false'},
    server: ${JSON.stringify({
      secureDefaults: (options.server as any)?.secureDefaults,
      secure: (options.server as any)?.secure,
    })},
  }

  const app = await createFeathersApp(nitroApp, config)

${put(swaggerEnabled, swaggerInitBlock)}
${put(keycloakEnabled, keycloakInitBlock)}

  ${put(auth, `// Init auth
  app.configure(authentication)
`)}
  ${put(mongo, `// Init mongodb
  app.configure(mongodb)
`)}

  // Init services
  ${services.map(service => `app.configure(${service.meta.importId})`).join('\n  ')}

  // Init plugins
  ${plugins.map(plugin => `app.configure(${plugin.meta.importId})`).join('\n  ')}

  // Init server modules (scan first, list second)
  ${serverModules.map(m => `await ${m.meta.importId}(app, { nitroApp, config, transports: config.transports, server: config.server, moduleOptions: ${JSON.stringify((m as any).options ?? null)} })`).join('\n  ')}

${put(exp, `  // Set up Express middleware for 404s and the error handler
  app.configure(expressErrorHandler)
`)}

  // IMPORTANT:
  // Mount Nitro routers *synchronously* after app.setup().
  // If we mount them in a deferred promise, early requests in dev can 404.
  await app.setup()

${puts([
  [koa, `  // Init koa router\n  createKoaRouter(app, '${restPath}')`],
  [exp, `  // Init express router\n  createExpressRouter(app, '${restPath}')`],
  [sio, `  // Init socket.io router\n  createSocketIoRouter(app)`],
])}

  nitroApp.hooks.hook('close', async () => app.teardown())
})
`
  }
}
