import type { ResolvedOptions } from '../../options'

export function getServerRbacContents(options: ResolvedOptions) {
  return async (): Promise<string> => {
    const keycloakEnabled = !!options.keycloak
    const keycloak = options.keycloak as any
    const keycloakClientId = keycloakEnabled ? keycloak.clientId : ''

    return `// ! Generated by nuxt-feathers-zod - do not change manually
import { existsSync, readFileSync, mkdirSync } from 'node:fs'
import { join, isAbsolute } from 'node:path'

function defaultRbacFile() {
  return {
    enabled: false,
    denyByDefault: true,
    roles: ['admin', 'editor', 'reader'],
    policies: {},
    updatedAt: new Date().toISOString(),
  }
}

function resolveServicesDirs(projectRoot, servicesDirs) {
  const dirs = (servicesDirs && servicesDirs.length) ? servicesDirs : ['services']
  return dirs.map((d) => {
    if (isAbsolute(d) || d.startsWith('\\\\')) return d
    return join(projectRoot, d)
  })
}

function getRbacPath(projectRoot, servicesDirs) {
  const dirsAbs = resolveServicesDirs(projectRoot, servicesDirs)
  const base = dirsAbs[0] || join(projectRoot, 'services')
  const nfzDir = join(base, '.nfz')
  if (!existsSync(nfzDir)) mkdirSync(nfzDir, { recursive: true })
  return join(nfzDir, 'rbac.json')
}

function readRbacFile(projectRoot, servicesDirs) {
  const p = getRbacPath(projectRoot, servicesDirs)
  if (!existsSync(p)) return defaultRbacFile()
  try {
    const raw = readFileSync(p, 'utf-8')
    const parsed = JSON.parse(raw || '{}')
    return {
      ...defaultRbacFile(),
      ...parsed,
      policies: parsed?.policies && typeof parsed.policies === 'object' ? parsed.policies : {},
    }
  } catch {
    return defaultRbacFile()
  }
}

function extractRolesLocal(user) {
  const roles = user?.roles
  if (Array.isArray(roles)) return roles.filter(Boolean).map(String)
  const permissions = user?.permissions
  if (Array.isArray(permissions)) return permissions.filter(Boolean).map(String)
  return []
}

function extractRolesKeycloak(user, clientId) {
  const out = new Set()
  const realmRoles = user?.realm_access?.roles
  if (Array.isArray(realmRoles)) realmRoles.forEach((r) => out.add(String(r)))
  if (clientId) {
    const clientRoles = user?.resource_access?.[clientId]?.roles
    if (Array.isArray(clientRoles)) clientRoles.forEach((r) => out.add(String(r)))
  }
  const scope = user?.scope
  if (typeof scope === 'string') scope.split(/\s+/).filter(Boolean).forEach(s => out.add(String(s)))
  return [...out]
}

function normalizeMethod(m) {
  if (m === 'find' || m === 'get' || m === 'create' || m === 'update' || m === 'patch' || m === 'remove') return m
  return null
}

export function nfzAuthorizeHook(opts) {
  const projectRoot = opts.projectRoot || process.cwd()
  const skip = new Set(opts.skipPaths || ['authentication', '_keycloak'])
  return async (context) => {
    const method = normalizeMethod(context.method)
    const path = (context.path || '').replace(/^[/]+/, '')
    if (!method || !path) return context
    if (skip.has(path)) return context

    const rbac = readRbacFile(projectRoot, opts.servicesDirs)
    if (!rbac.enabled) return context

    const required = rbac.policies?.[path]?.[method]
    if (!required || required.length === 0) {
      if (rbac.denyByDefault) throw new Error('Forbidden')
      return context
    }

    const user = context.params?.user
    const roles = opts.provider === 'keycloak'
      ? extractRolesKeycloak(user, opts.keycloakClientId || '${keycloakClientId}')
      : extractRolesLocal(user)

    const allow = roles.some(r => required.includes(r))
    if (!allow) throw new Error('Forbidden')
    return context
  }
}
`
  }
}
