import type { ResolvedOptions } from '../../options'

export function getServerRbacDtsContents(_options: ResolvedOptions) {
  return async (): Promise<string> => {
    return `// ! Generated by nuxt-feathers-zod - do not change manually
import type { HookContext } from '@feathersjs/feathers'

export type RbacMethod = 'find' | 'get' | 'create' | 'update' | 'patch' | 'remove'
export type RbacPolicies = Record<string, Partial<Record<RbacMethod, string[]>>>

export type RbacFile = {
  enabled: boolean
  denyByDefault: boolean
  roles: string[]
  policies: RbacPolicies
  updatedAt?: string
}

export type NfzAuthorizeHookOptions = {
  projectRoot?: string
  servicesDirs?: string[]
  provider: 'local' | 'keycloak'
  keycloakClientId?: string
  skipPaths?: string[]
}

export function nfzAuthorizeHook(opts: NfzAuthorizeHookOptions): (context: HookContext) => Promise<HookContext>
`
  }
}
