import type { ResolvedOptions } from '../../options'
import type { RestOptions } from '../../options/transports/rest'

export function getServerRestBridgeContents(options: ResolvedOptions) {
  return (): string => {
    const transports = options?.transports
    const rest = !!transports?.rest
    const framework = (transports?.rest as RestOptions)?.framework
    const restPath = (transports?.rest as RestOptions)?.path || '/feathers'

    if (!rest || framework !== 'express' || !restPath) {
      return `// ! Generated by nuxt-feathers-zod - do not change manually
import { defineEventHandler } from 'h3'

export default defineEventHandler(() => undefined)
`
    }

    return `// ! Generated by nuxt-feathers-zod - do not change manually
import { waitForNfzRuntimeInstance } from 'nuxt-feathers-zod/server-instance-registry'
import { createError, defineEventHandler } from 'h3'

const REST_PREFIX = ${JSON.stringify(restPath)}
const READY_TIMEOUT_MS = 15000

function ensureLeadingSlash(value) {
  if (!value)
    return '/'
  return value.startsWith('/') ? value : '/' + value
}

function rewriteLegacyMongoAliases(pathname) {
  const normalized = ensureLeadingSlash(String(pathname || '/'))

  if (normalized === '/mongo' || normalized === '/mongo/')
    return '/mongo/databases'

  return normalized
}

function stripRestPrefix(url) {
  const source = String(url || '')
  if (!source)
    return '/'

  const queryIndex = source.indexOf('?')
  const pathOnly = queryIndex >= 0 ? source.slice(0, queryIndex) : source
  const query = queryIndex >= 0 ? source.slice(queryIndex) : ''
  const normalizedPrefix = REST_PREFIX.length > 1 && REST_PREFIX.endsWith('/') ? REST_PREFIX.slice(0, -1) : REST_PREFIX

  if (normalizedPrefix === '/')
    return rewriteLegacyMongoAliases(ensureLeadingSlash(pathOnly)) + query

  if (!pathOnly.startsWith(normalizedPrefix))
    return source

  const stripped = pathOnly.slice(normalizedPrefix.length) || '/'
  return rewriteLegacyMongoAliases(ensureLeadingSlash(stripped)) + query
}

export default defineEventHandler(async (event) => {
  let runtime
  try {
    runtime = await waitForNfzRuntimeInstance('default', READY_TIMEOUT_MS)
  }
  catch {
    event.node.res.setHeader('retry-after', '1')
    throw createError({
      statusCode: 503,
      statusMessage: 'Feathers runtime unavailable',
      message: 'The embedded Feathers runtime is not ready.',
    })
  }

  const app = runtime.app
  if (typeof app !== 'function') {
    throw createError({
      statusCode: 503,
      statusMessage: 'Feathers runtime unavailable',
      message: 'The embedded Express application is not ready.',
    })
  }

  const req = event.node.req
  const res = event.node.res
  const originalUrl = req.url || '/'
  const originalOriginalUrl = req.originalUrl
  const nextUrl = stripRestPrefix(originalUrl)

  req.url = nextUrl
  req.originalUrl = nextUrl

  try {
    await new Promise((resolve, reject) => {
      let settled = false
      const done = (error) => {
        if (settled)
          return
        settled = true
        if (error)
          reject(error)
        else
          resolve(undefined)
      }

      res.once('finish', () => done())
      res.once('close', () => done())

      try {
        app(req, res, done)
      }
      catch (error) {
        reject(error)
      }
    })

    if (!res.headersSent && !res.writableEnded) {
      res.statusCode = res.statusCode && res.statusCode !== 200 ? res.statusCode : 404
      res.setHeader('content-type', 'application/json; charset=utf-8')
      res.end(JSON.stringify({
        name: 'NotFound',
        message: '[feathers] Page not found: ' + nextUrl,
        code: 404,
        className: 'not-found',
      }))
    }
  }
  finally {
    req.url = originalUrl
    req.originalUrl = originalOriginalUrl
  }
})
`
  }
}
