import type { ResolvedOptions } from '../../options'
import type { RestOptions } from '../../options/transports/rest'

export function getServerRestBridgeContents(options: ResolvedOptions): () => string {
  return (): string => {
    const transports = options?.transports
    const rest = !!transports?.rest
    const framework = (transports?.rest as RestOptions)?.framework
    const restPath = (transports?.rest as RestOptions)?.path || '/feathers'

    if (!rest || framework !== 'express' || !restPath) {
      return `// ! Generated by nuxt-feathers-zod - do not change manually
import { defineEventHandler } from 'h3'

export default defineEventHandler(() => undefined)
`
    }

    return `// ! Generated by nuxt-feathers-zod - do not change manually
// @ts-check
import { getNfzRuntimeInstance } from 'nuxt-feathers-zod/server-instance-registry'
import { defineEventHandler } from 'h3'

const REST_PREFIX = ${JSON.stringify(restPath)}

/**
 * @typedef {object} JsonPayload
 * @property {string} name
 * @property {string} message
 * @property {number} code
 * @property {string} className
 * @property {string} [state]
 * @property {string} [causeId]
 */

/**
 * @typedef {object} ErrorLike
 * @property {unknown} [name]
 * @property {unknown} [message]
 * @property {unknown} [code]
 * @property {unknown} [statusCode]
 * @property {unknown} [className]
 */

/**
 * @typedef {object} NfzRequest
 * @property {string} [url]
 * @property {string} [originalUrl]
 */

/**
 * @typedef {object} NfzResponse
 * @property {boolean} headersSent
 * @property {boolean} writableEnded
 * @property {number} statusCode
 * @property {(name: string, value: string) => void} setHeader
 * @property {(body?: string) => void} end
 * @property {(event: 'finish' | 'close', listener: (error?: unknown) => void) => void} once
 * @property {(event: 'finish' | 'close', listener: (error?: unknown) => void) => void} off
 */

/**
 * @typedef {object} NfzEvent
 * @property {{ req: NfzRequest, res: NfzResponse }} node
 */

/**
 * @param {string | null | undefined} value
 * @returns {string}
 */
function ensureLeadingSlash(value) {
  if (!value)
    return '/'
  return value.startsWith('/') ? value : '/' + value
}

/**
 * @param {string | null | undefined} pathname
 * @returns {string}
 */
function rewriteLegacyMongoAliases(pathname) {
  const normalized = ensureLeadingSlash(pathname || '/')

  if (normalized === '/mongo' || normalized === '/mongo/')
    return '/mongo/databases'

  return normalized
}

/**
 * @param {string | null | undefined} url
 * @returns {string}
 */
function stripRestPrefix(url) {
  const source = url || ''
  if (!source)
    return '/'

  const queryIndex = source.indexOf('?')
  const pathOnly = queryIndex >= 0 ? source.slice(0, queryIndex) : source
  const query = queryIndex >= 0 ? source.slice(queryIndex) : ''
  const normalizedPrefix = REST_PREFIX.length > 1 && REST_PREFIX.endsWith('/') ? REST_PREFIX.slice(0, -1) : REST_PREFIX

  if (normalizedPrefix === '/')
    return rewriteLegacyMongoAliases(ensureLeadingSlash(pathOnly)) + query

  if (!pathOnly.startsWith(normalizedPrefix))
    return source

  const stripped = pathOnly.slice(normalizedPrefix.length) || '/'
  return rewriteLegacyMongoAliases(ensureLeadingSlash(stripped)) + query
}

/**
 * @param {NfzEvent} event
 * @param {number} statusCode
 * @param {JsonPayload} payload
 * @param {string} [retryAfter]
 * @returns {void}
 */
function sendJson(event, statusCode, payload, retryAfter) {
  const res = event.node.res
  if (res.headersSent || res.writableEnded)
    return

  res.statusCode = statusCode
  res.setHeader('content-type', 'application/json; charset=utf-8')
  if (retryAfter)
    res.setHeader('retry-after', retryAfter)
  res.end(JSON.stringify(payload))
}

/**
 * @param {unknown} error
 * @returns {JsonPayload}
 */
function toSafeError(error) {
  const input = /** @type {ErrorLike} */ (
    error && typeof error === 'object' ? error : {}
  )
  const statusCandidate = typeof input.code === 'number'
    ? input.code
    : typeof input.statusCode === 'number'
      ? input.statusCode
      : 500
  const code = statusCandidate >= 400 && statusCandidate <= 599 ? statusCandidate : 500

  return {
    name: typeof input.name === 'string' && input.name ? input.name : 'GeneralError',
    message: code >= 500
      ? 'The Feathers request could not be completed.'
      : typeof input.message === 'string' && input.message
        ? input.message
        : 'The Feathers request could not be completed.',
    code,
    className: typeof input.className === 'string' && input.className
      ? input.className
      : code === 404
        ? 'not-found'
        : 'general-error',
  }
}

/**
 * @param {NfzEvent} event
 * @returns {Promise<void>}
 */
async function handleRestBridge(event) {
  const runtime = getNfzRuntimeInstance('default')

  if (!runtime || runtime.status === 'initializing') {
    sendJson(event, 503, {
      name: 'Unavailable',
      message: 'The embedded Feathers runtime is initializing.',
      code: 503,
      className: 'unavailable',
      state: runtime?.status || 'absent',
    }, '1')
    return
  }

  if (runtime.status === 'failed') {
    sendJson(event, 503, {
      name: 'Unavailable',
      message: 'The embedded Feathers runtime failed to start.',
      code: 503,
      className: 'unavailable',
      state: 'failed',
      causeId: runtime.failureId || 'nfz-runtime-failed',
    }, '1')
    return
  }

  if (runtime.status !== 'ready') {
    sendJson(event, 503, {
      name: 'Unavailable',
      message: 'The embedded Feathers runtime is unavailable.',
      code: 503,
      className: 'unavailable',
      state: runtime.status,
    }, '1')
    return
  }

  const app = runtime.app
  if (typeof app !== 'function') {
    sendJson(event, 503, {
      name: 'Unavailable',
      message: 'The embedded Express application is not ready.',
      code: 503,
      className: 'unavailable',
      state: 'ready-without-express-app',
    }, '1')
    return
  }

  const req = event.node.req
  const res = event.node.res
  const originalUrl = req.url || '/'
  const originalOriginalUrl = req.originalUrl
  const nextUrl = stripRestPrefix(originalUrl)

  req.url = nextUrl
  req.originalUrl = nextUrl

  try {
    await new Promise((resolve, reject) => {
      let settled = false

      const cleanup = () => {
        res.off('finish', done)
        res.off('close', done)
      }

      /**
       * @param {unknown} [error]
       * @returns {void}
       */
      const done = (error) => {
        if (settled)
          return

        settled = true
        cleanup()

        if (error)
          reject(error)
        else
          resolve(undefined)
      }

      res.once('finish', done)
      res.once('close', done)

      try {
        app(req, res, done)
      }
      catch (error) {
        done(error)
      }
    })
  }
  catch (error) {
    const payload = toSafeError(error)
    sendJson(event, payload.code, payload)
  }
  finally {
    req.url = originalUrl
    req.originalUrl = originalOriginalUrl
  }

  if (!res.headersSent && !res.writableEnded) {
    sendJson(event, 404, {
      name: 'NotFound',
      message: '[feathers] Page not found: ' + nextUrl,
      code: 404,
      className: 'not-found',
    })
  }
}

export default defineEventHandler(handleRestBridge)
`
  }
}
