import type { ResolvedOptions } from '../../options'

export function getSecureDefaultsModuleContents(_options: ResolvedOptions) {
  return async (): Promise<string> => {
    return `// ! Generated by nuxt-feathers-zod - do not change manually
// Server module: secure defaults (Express)
// Legacy compatibility module; normalized secure settings now resolve to explicit built-in modules.
// - CORS (on by default)
// - helmet
// - compression
// - json + urlencoded body parsing
// - optional static serving

import cors from 'cors'
import helmet from 'helmet'
import compression from 'compression'
import { json, urlencoded, serveStatic } from '@feathersjs/express'

export default async function secureDefaults(app, ctx = {}) {
  if (ctx?.moduleOptions === false)
    return
  const framework = ctx?.transports?.rest?.framework || ctx?.framework || app?.get?.('framework')
  if (framework && framework !== 'express')
    return

  const server = ctx?.server || {}
  const enabled = server.secureDefaults !== false
  const secure = { ...(server.secure || {}), ...(ctx?.moduleOptions || {}) }

  const bp = secure.bodyParser || {}
  const jsonOpt = bp.json
  const urlOpt = bp.urlencoded
  const enableJson = enabled ? (jsonOpt !== false) : (jsonOpt && jsonOpt !== false)
  const enableUrl = enabled ? (urlOpt !== false) : (urlOpt && urlOpt !== false)

  if (enableJson)
    app.use(json(typeof jsonOpt === 'object' ? jsonOpt : undefined))
  if (enableUrl)
    app.use(urlencoded(typeof urlOpt === 'object' ? urlOpt : { extended: true }))

  if (!enabled)
    return

  const corsOpt = secure.cors
  if (corsOpt)
    app.use(cors(typeof corsOpt === 'object' ? corsOpt : undefined))

  const helmetOpt = secure.helmet
  if (helmetOpt)
    app.use(helmet(typeof helmetOpt === 'object' ? helmetOpt : undefined))

  const compressionOpt = secure.compression
  if (compressionOpt)
    app.use(compression(typeof compressionOpt === 'object' ? compressionOpt : undefined))

  const serveStaticOpt = secure.serveStatic
  if (serveStaticOpt && serveStaticOpt !== false) {
    const staticPath = (typeof serveStaticOpt === 'object' && serveStaticOpt.path) ? serveStaticOpt.path : '/'
    const staticDir = (typeof serveStaticOpt === 'object' && serveStaticOpt.dir) ? serveStaticOpt.dir : 'public'
    app.use(staticPath, serveStatic(staticDir))
  }
}
`
  }
}
