import type { ResolvedOptions } from '../../options'
import type { DefaultAuthOptions } from '../../options/authentication'
import type { RestOptions } from '../../options/transports/rest'
import { put, puts } from '../utils'

export function getServerTypesContents(options: ResolvedOptions) {
  return (): string => {
    const transports = options?.transports
    const rest = !!transports?.rest
    const exp = (transports?.rest as RestOptions).framework === 'express'
    const koa = (transports?.rest as RestOptions).framework === 'koa'

    const mongo = !!options.database?.mongo

    let entity, entityImport
    const auth = options?.auth as DefaultAuthOptions
    if (auth) {
      entity = auth.entity
      entityImport = auth.entityImport
    }

    return `// ! Generated by nuxt-feathers-zod - do not change manually
import type { ${put(!rest, `Application as FeathersApplication, `)}HookContext as FeathersHookContext, NextFunction } from '@feathersjs/feathers'
${put(mongo, `import type { Db, MongoClient } from 'mongodb'`)}
${puts([
  [koa, `import type { Application as FeathersApplication } from '@feathersjs/koa'`],
  [exp, `import type { Application as FeathersApplication } from '@feathersjs/express'`],
])}
${put(auth && entityImport?.from, `import type { User } from '${entityImport?.from}'`)}
import type { NitroApp } from 'nitropack'

export type { NextFunction }

export interface Configuration {
  framework?: 'express' | 'koa'
  websocket?: boolean${put(mongo, `
  mongodbClient: Promise<Db>
  mongodbDb: Db
  mongodbConnection: MongoClient`)}
}

export interface ServiceTypes {}

export interface ApplicationAddons {
  nitroApp?: NitroApp
}

export type Application = FeathersApplication<ServiceTypes, Configuration> & ApplicationAddons
export type HookContext<S = any> = FeathersHookContext<Application, S>
export type FeathersServerPlugin = Parameters<Application['configure']>['0']

export interface FeathersServerModuleContext {
  nitroApp: NitroApp
  config: Record<string, any>
  transports: Record<string, any>
  server: Record<string, any>
  moduleOptions?: any
}

export type FeathersServerModule = (app: Application, ctx: FeathersServerModuleContext) => void | Promise<void>

export declare function defineFeathersServerPlugin(def: FeathersServerPlugin): FeathersServerPlugin
export declare function defineFeathersServerModule(def: FeathersServerModule): FeathersServerModule
${put(auth, `
declare module '@feathersjs/feathers' {
  interface Params {
    ${entity}?: ${entityImport?.as}
  }
}`)}
`
  }
}
