import type { ResolvedOptions } from '../../options'

export function getServerRuntimeContents(_options: ResolvedOptions) {
  return (): string => {
    return `// ! Generated by nuxt-feathers-zod - do not change manually

export function defineFeathersServerPlugin(def) {
  return def
}

export function defineFeathersServerModule(def) {
  return def
}
`
  }
}
