import type { ResolvedOptions } from '../../options'
import { put } from '../utils'

export function getServerValidatorContents(options: ResolvedOptions) {
  return (): string => {
    const formats = options?.validator?.formats
    const mongo = !!options?.database?.mongo

    return `// ! Generated by nuxt-feathers-zod - do not change manually
// For more information about this file see https://dove.feathersjs.com/guides/cli/validators.html

${put(mongo, `import { keywordObjectId } from '@feathersjs/mongodb'`)}
import { addFormats, Ajv } from '@feathersjs/schema'

const formats = [
  '${formats?.join(`',
  '`)}'
]

export const dataValidator = addFormats(new Ajv({}), formats)

export const queryValidator = addFormats(
  new Ajv({
    coerceTypes: true,
  }),
  formats,
)  
${put(mongo, `
dataValidator.addKeyword(keywordObjectId)
queryValidator.addKeyword(keywordObjectId)`)}
`
  }
}

export function getServerValidatorTypesContents(_options: ResolvedOptions) {
  return (): string => `// ! Generated by nuxt-feathers-zod - do not change manually
import type { Ajv } from '@feathersjs/schema'

export declare const dataValidator: Ajv
export declare const queryValidator: Ajv
`
}
