import type { ResolvedOptions } from '../../options'
import { put } from '../utils'

export function getServerValidatorContents(options: ResolvedOptions) {
  return (): string => {
    const formats = options?.validator?.formats
    const mongo = !!options?.database?.mongo

    return `// ! Generated by nuxt-feathers-zod - do not change manually
// For more information about this file see https://dove.feathersjs.com/guides/cli/validators.html

${put(mongo, `import { keywordObjectId } from '@feathersjs/mongodb'`)}
import type { FormatsPluginOptions } from '@feathersjs/schema'
import { addFormats, Ajv } from '@feathersjs/schema'

const formats: FormatsPluginOptions = [
  '${formats?.join(`',\n  '`)}'
]

export const dataValidator: Ajv = addFormats(new Ajv({}), formats)

export const queryValidator: Ajv = addFormats(
  new Ajv({
    coerceTypes: true,
  }),
  formats,
)  
${put(mongo, `
dataValidator.addKeyword(keywordObjectId)
queryValidator.addKeyword(keywordObjectId)`)}`
  }
}
