/**
 * NFZ runtime as a single readable Feathers app.
 *
 * This file is intentionally not imported by the module. It is a production-oriented
 * comparison artifact to understand how the generated NFZ embedded runtime maps to
 * a classic app.js/app.ts generated by the official Feathers CLI.
 */
import type { Application, HookContext, Params } from '@feathersjs/feathers'
import { feathers } from '@feathersjs/feathers'
import { MemoryService } from '@feathersjs/memory'
import { MongoDBService } from '@feathersjs/mongodb'
import { koa, rest, bodyParser, errorHandler, serveStatic } from '@feathersjs/koa'
import socketio from '@feathersjs/socketio'
import { authentication, AuthenticationService, JWTStrategy } from '@feathersjs/authentication'
import { LocalStrategy } from '@feathersjs/authentication-local'
import { MongoClient } from 'mongodb'

type User = {
  _id: string
  userId: string
  password?: string
  roles?: string[]
}

type Message = {
  id?: number
  text: string
  createdAt: string
  userId?: string
}

type ServiceTypes = {
  users: MongoDBService<User>
  messages: MemoryService<Message>
  authentication: AuthenticationService
}

type NfzSingleFileApp = Application<ServiceTypes>

export interface NfzRuntimeSingleFileOptions {
  mongodbUrl: string
  mongodbDatabase: string
  restPath?: string
  socketioPath?: string
  publicDir?: string
  authSecret: string
}

function requireAuth(context: HookContext) {
  if (!context.params.authentication && !context.params.user) {
    throw new Error('Authentication required')
  }
  return context
}

function createAuthentication(app: NfzSingleFileApp, secret: string) {
  const auth = new AuthenticationService(app)
  auth.register('jwt', new JWTStrategy())
  auth.register('local', new LocalStrategy())

  app.set('authentication', {
    secret,
    entity: 'user',
    service: 'users',
    authStrategies: ['jwt', 'local'],
    jwtOptions: {
      header: { typ: 'access' },
      audience: 'https://nuxt-feathers-zod.local',
      issuer: 'nuxt-feathers-zod',
      algorithm: 'HS256',
      expiresIn: '1d',
    },
    local: {
      usernameField: 'userId',
      passwordField: 'password',
    },
  })

  app.use('authentication', auth)
  app.configure(authentication(app.get('authentication')))
}

export async function createNfzRuntimeSingleFileApp(options: NfzRuntimeSingleFileOptions) {
  const restPath = options.restPath ?? '/feathers'
  const socketioPath = options.socketioPath ?? '/socket.io'

  const mongoClient = new MongoClient(options.mongodbUrl)
  await mongoClient.connect()
  const mongoDb = mongoClient.db(options.mongodbDatabase)

  const app = koa(feathers<ServiceTypes>()) as NfzSingleFileApp

  // Equivalent NFZ runtime state usually injected through generated .nuxt/feathers files.
  app.set('mongodbClient', Promise.resolve(mongoDb))
  app.set('mongodbDb', mongoDb)
  app.set('restPath', restPath)
  app.set('socketioPath', socketioPath)

  // Equivalent to generated server modules / secure defaults.
  app.use(errorHandler())
  app.use(bodyParser())
  if (options.publicDir) app.use(serveStatic(options.publicDir))

  // Feathers transports. In NFZ, these are mounted behind the Nuxt/Nitro lifecycle.
  app.configure(rest())
  app.configure(socketio({ path: socketioPath }))

  // Services: in NFZ these registrations are generated from feathers.servicesDirs.
  app.use('users', new MongoDBService<User>({
    Model: Promise.resolve(mongoDb.collection<User>('users')),
    paginate: { default: 20, max: 100 },
  }))

  app.use('messages', new MemoryService<Message>({
    paginate: { default: 20, max: 100 },
    multi: ['remove'],
  }))

  createAuthentication(app, options.authSecret)

  app.service('messages').hooks({
    before: {
      all: [requireAuth],
      create: [async (context) => {
        const params = context.params as Params & { user?: User }
        context.data = {
          ...context.data,
          createdAt: new Date().toISOString(),
          userId: params.user?.userId,
        }
        return context
      }],
    },
  })

  app.teardown(async () => {
    await mongoClient.close()
  })

  return app
}

// Standalone usage, close to a Feathers CLI generated app.ts.
if (import.meta.url === `file://${process.argv[1]}`) {
  const app = await createNfzRuntimeSingleFileApp({
    mongodbUrl: process.env.MONGODB_URL ?? 'mongodb://127.0.0.1:27017/nfz-runtime-demo',
    mongodbDatabase: process.env.MONGODB_DATABASE ?? 'nfz-runtime-demo',
    authSecret: process.env.FEATHERS_AUTH_SECRET ?? 'change-me-in-production',
  })

  const port = Number(process.env.PORT ?? 3030)
  await app.listen(port)
  console.log(`[nfz-runtime-single-file] Feathers app listening on http://localhost:${port}`)
}
