import type { ResolvedOptions } from '../../options'
import type { DefaultAuthOptions } from '../../options/authentication'
import { put } from '../utils'

export function getClientAuthContents(options: ResolvedOptions) {
  return (): string => {
    const jwt = (options.auth as DefaultAuthOptions)?.authStrategies?.includes('jwt') || Boolean((options.client as any)?.remote?.auth?.enabled)

    return `// ! Generated by nuxt-feathers-zod - do not change manually
import type { ClientApplication } from './client'
import {${put(jwt, `useCookie,`)} useRuntimeConfig } from '#app'
import authenticationClient, { type AuthenticationClientOptions } from '@feathersjs/authentication-client'
import { klona } from 'klona'

export function authentication(client: ClientApplication) {
  const pub = (useRuntimeConfig().public as any)
  const clientOptions = pub._feathers?.auth?.client ?? {
    service: pub._feathers?.client?.remote?.auth?.servicePath ?? 'authentication',
    storageKey: pub._feathers?.client?.remote?.auth?.storageKey ?? 'feathers-jwt',
  }
  const authClientOptions = klona(clientOptions) as AuthenticationClientOptions
 
${put(jwt, `  // Store JWT in a cookie for SSR.
  const jwt = useCookie<string | null>(authClientOptions.storageKey)
  const storage = {
    getItem: () => jwt.value,
    setItem: (key: string, val: string) => (jwt.value = val),
    removeItem: () => (jwt.value = null),
  }
  authClientOptions.storage = storage
`)}
  client.configure(authenticationClient(authClientOptions))
}
`
  }
}
