import type { ResolvedOptions } from '../../options'
import type { DefaultAuthOptions } from '../../options/authentication'
import { put } from '../utils'

export function getClientAuthContents(options: ResolvedOptions) {
  return (): string => {
    const jwt = (options.auth as DefaultAuthOptions)?.authStrategies?.includes('jwt') || Boolean((options.client as any)?.remote?.auth?.enabled)

    return `// ! Generated by nuxt-feathers-zod - do not change manually
import type { ClientApplication } from './client'
import {${put(jwt, `useCookie,`)} useRuntimeConfig } from '#app'

export interface NativeAuthenticationClientOptions {
  service?: string
  path?: string
  storageKey?: string
  storage?: {
    getItem: (key: string) => string | null | Promise<string | null>
    setItem: (key: string, value: string) => void | Promise<void>
    removeItem: (key: string) => void | Promise<void>
  }
  [key: string]: any
}

export function authentication(client: ClientApplication) {
  const pub = (useRuntimeConfig().public as any)
  const clientOptions = pub._feathers?.auth?.client ?? {
    service: pub._feathers?.client?.remote?.auth?.servicePath ?? 'authentication',
    storageKey: pub._feathers?.client?.remote?.auth?.storageKey ?? 'feathers-jwt',
  }
  const authClientOptions = { ...clientOptions } as NativeAuthenticationClientOptions
 
${put(jwt, `  // Store JWT in a cookie for SSR.
  const jwt = useCookie<string | null>(authClientOptions.storageKey || 'feathers-jwt')
  const storage = {
    getItem: () => jwt.value,
    setItem: (_key: string, val: string) => (jwt.value = val),
    removeItem: () => (jwt.value = null),
  }
  authClientOptions.storage = storage
`)}
  configureNativeAuthenticationClient(client, authClientOptions)
}

function configureNativeAuthenticationClient(client: ClientApplication, options: NativeAuthenticationClientOptions) {
  const servicePath = String(options.service || options.path || 'authentication').replace(/^\\/+/, '')
  const storageKey = options.storageKey || 'feathers-jwt'
  const storage = options.storage || createBrowserStorage()

  const auth = {
    options: { ...options, service: servicePath, storageKey, storage },
    async getAccessToken() {
      return await storage.getItem(storageKey)
    },
    async setAccessToken(accessToken: string) {
      await storage.setItem(storageKey, accessToken)
      return accessToken
    },
    async removeAccessToken() {
      await storage.removeItem(storageKey)
    },
  }

  ;(client as any).authentication = auth
  ;(client as any).set?.('authentication', auth)

  ;(client as any).authenticate = async (authentication: any, params?: any) => {
    const result = await (client as any).service(servicePath).create(authentication, params)
    const accessToken = getAccessTokenFromResult(result)
    if (accessToken)
      await auth.setAccessToken(accessToken)
    return result
  }

  ;(client as any).reAuthenticate = async (_force?: boolean, strategy = 'jwt') => {
    const accessToken = await auth.getAccessToken()
    if (!accessToken)
      throw new Error('[nuxt-feathers-zod] No access token available for reAuthenticate().')
    return await (client as any).authenticate({ strategy, accessToken })
  }

  ;(client as any).logout = async (params?: any) => {
    try {
      await (client as any).service(servicePath).remove(null, params)
    }
    finally {
      await auth.removeAccessToken()
    }
  }
}

function createBrowserStorage() {
  return {
    getItem(key: string) {
      if (typeof window === 'undefined') return null
      return window.localStorage.getItem(key)
    },
    setItem(key: string, value: string) {
      if (typeof window !== 'undefined') window.localStorage.setItem(key, value)
    },
    removeItem(key: string) {
      if (typeof window !== 'undefined') window.localStorage.removeItem(key)
    },
  }
}

function getAccessTokenFromResult(result: any): string | null {
  return result?.accessToken || result?.access_token || result?.token || result?.jwt || null
}
`
  }
}
