import type { ResolvedOptions } from '../../options'
import type { DefaultAuthOptions } from '../../options/authentication'
import { put } from '../utils'

export function getClientContents(options: ResolvedOptions) {
  return (): string => {
    const apiType = 'ClientApplication'

    let entity: string | undefined
    let entityImport: DefaultAuthOptions['entityImport'] | undefined
    const auth = options?.auth as DefaultAuthOptions | false
    if (auth) {
      entity = auth.entity
      entityImport = auth.entityImport
    }

    const entityImportStatement = auth && entityImport?.from && entityImport?.as
      ? `import type { ${entityImport.as} } from '${entityImport.from}'`
      : ''

    const entityTypeName = entityImport?.as || 'unknown'

    return `// ! Generated by nuxt-feathers-zod - do not change manually
  ${put(entityImportStatement, entityImportStatement)}
  import type { Application, TransportConnection } from '@feathersjs/feathers'
  
  export interface Configuration {
    connection: TransportConnection<ServiceTypes>
  }
  
  export interface ServiceTypes {}
  
  export type ClientApplication = Application<ServiceTypes, Configuration>
  
  export type FeathersClientPlugin = Parameters<ClientApplication['configure']>['0']
  
  export function defineFeathersClientPlugin(def: FeathersClientPlugin): FeathersClientPlugin {
    return def;
  }
  ${put(auth && entity && entityImport?.as, `  
  declare module '@feathersjs/feathers' {
    interface Params {
      ${entity}?: ${entityTypeName}
    }
  }`)}
  
  declare module '#app' {
    interface NuxtApp {
      $api: ${apiType}
      $client: ClientApplication
    }
  }
  
  declare module 'vue' {
    interface ComponentCustomProperties {
      $api: ${apiType}
      $client: ClientApplication
    }
  }
  `
  }
}
