import type { Resolver } from '@nuxt/kit'
import type { ResolvedOptions } from '../../options'
import type { ClientOptions } from '../../options/client'
import type { RestOptions } from '../../options/transports/rest'
import type { WebsocketOptions } from '../../options/transports/websocket'
import { put, puts } from '../utils'

export function getClientConnectionContents(options: ResolvedOptions, resolver: Resolver) {
  return (): string => {
    const pinia = !!(options.client as ClientOptions)?.pinia
    const transports = options?.transports
    const rest = !!transports?.rest
    const sio = !!transports?.websocket

    const restPath = (transports?.rest as RestOptions)?.path
    const websocketOptions = (transports?.websocket as WebsocketOptions) || undefined
    const sioPath = websocketOptions?.path
    const sioConnectTimeout = websocketOptions?.connectTimeout
    const sioTransports = websocketOptions?.transports

    // NOTE: Avoid template-regex escaping issues in generated code.
    // Always inject strings via JSON.stringify and keep runtime helpers regex-free.
    const defaultRestPath = JSON.stringify(restPath ?? '/')
    const defaultSioPath = JSON.stringify(sioPath ?? '/socket.io')
    const defaultSioConnectTimeout = JSON.stringify(sioConnectTimeout ?? 45000)
    const defaultSioTransports = JSON.stringify(sioTransports ?? ['websocket'])

    return `// ! Generated by nuxt-feathers-zod - do not change manually
// You can set it in nuxt.config.js with the feathers.transports option
import type { ClientApplication } from './client'
${puts([
  [rest, `import rest from '@feathersjs/rest-client'\nimport { $fetch } from 'ofetch'`],
  [sio, `import socketioClient from '@feathersjs/socketio-client'\nimport { io } from 'socket.io-client'`],
  [rest, `import { OFetch } from '${put(pinia, 'feathers-pinia', resolver.resolve('./runtime/adapters/ofetch'))}'`],
])}

export function connection(origin?: string, overrides?: { restPath?: string, websocketPath?: string, transport?: 'auto' | 'rest' | 'socketio' }) {
  return function (client: ClientApplication) {
    const restPathOverride = overrides?.restPath
    const websocketPathOverride = overrides?.websocketPath
    const transportOverride = overrides?.transport ?? 'auto'

    // base URL parsing:
    // - embedded mode: origin is same-origin (e.g. window.location.origin)
    // - remote mode: origin can be a full URL and may include a pathname prefix (e.g. https://api.tld/api/v1)
    // For stability (and Socket.IO expectations), separate origin and prefix.
    if (!origin)
      throw new Error('[nuxt-feathers-zod] connection(): base url is required')

    const base = new URL(origin)
    const originOnly = base.origin
    const prefix = base.pathname === '/' ? '' : trimTrailingSlash(base.pathname)

    // Defaults come from module transport config (generated constants).
    const DEFAULT_REST_PATH = ${defaultRestPath}
    const DEFAULT_SOCKET_PATH = ${defaultSioPath}
    const DEFAULT_SOCKET_CONNECT_TIMEOUT = ${defaultSioConnectTimeout}
    const DEFAULT_SOCKET_TRANSPORTS = ${defaultSioTransports}

    // Path resolution rules:
    // 1) explicit override always wins
    // 2) if base url contains a prefix (pathname), prefer it for REST and prefix socket path
    // 3) otherwise fall back to module defaults
    const restPathResolved = normalizePath(restPathOverride ?? (prefix || DEFAULT_REST_PATH))
    const websocketPathResolved = normalizePath(websocketPathOverride ?? (prefix ? joinPath(prefix, DEFAULT_SOCKET_PATH) : DEFAULT_SOCKET_PATH))

${puts([
  [rest, `    const restConnectionResolved = rest(new URL(restPathResolved, originOnly).href).fetch($fetch, OFetch)`],
  [sio, `    const rawSocketResolved = io(originOnly, { path: websocketPathResolved, connectTimeout: DEFAULT_SOCKET_CONNECT_TIMEOUT, transports: DEFAULT_SOCKET_TRANSPORTS })
    const sioConnectionResolved = socketioClient(rawSocketResolved)`],
])}

    const connection = (() => {
      // transportOverride:
      // - 'rest': force REST (useful for SSR + remote REST)
      // - 'socketio': force Socket.IO (browser only; falls back to REST if websocket transport disabled)
      // - 'auto': keep default behavior (SSR -> REST, browser -> Socket.IO when enabled)
      if (transportOverride === 'rest')
        return ${put(rest, 'restConnectionResolved', 'undefined as any')}
      if (transportOverride === 'socketio')
        return ${put(sio, 'sioConnectionResolved', put(rest, 'restConnectionResolved', 'undefined as any'))}
      // auto
      return ${put(rest && sio, "import.meta.server ? restConnectionResolved : sioConnectionResolved", puts([
        [rest || !sio, put(rest, 'restConnectionResolved', 'undefined as any')],
        [sio, put(sio, 'sioConnectionResolved', put(rest, 'restConnectionResolved', 'undefined as any'))],
      ]))}
    })()


    client.configure(connection)

    client.set('connection', connection)
${puts([[sio, `    if (connection === sioConnectionResolved)
      client.set('socket', rawSocketResolved)`]])}
  }
}

// ---- helpers (regex-free) ----
function trimTrailingSlash(value: string) {
  let s = value
  while (s.length > 1 && s.endsWith('/'))
    s = s.slice(0, -1)
  return s
}

function ensureLeadingSlash(value: string) {
  if (!value)
    return '/'
  // IMPORTANT: keep generated code free of template-literals (backticks)
  // to avoid breaking the outer template string of this generator.
  return value.startsWith('/') ? value : '/' + value
}

function normalizePath(value: string) {
  const s = ensureLeadingSlash(value)
  // keep '/' as-is; otherwise remove trailing slashes
  return s === '/' ? s : trimTrailingSlash(s)
}

function joinPath(a: string, b: string) {
  const left = a === '/' ? '' : trimTrailingSlash(a)
  const right = ensureLeadingSlash(b)
  // IMPORTANT: keep generated code free of template-literals (backticks)
  // to avoid breaking the outer template string of this generator.
  return left + right
}
`
  }
}
