import type { Resolver } from '@nuxt/kit'
import type { ResolvedOptions } from '../../options'
import type { RestOptions } from '../../options/transports/rest'
import type { WebsocketOptions } from '../../options/transports/websocket'
import { put, puts } from '../utils'

export function getClientConnectionContents(options: ResolvedOptions, resolver: Resolver) {
  return (): string => {
    const transports = options?.transports
    const rest = !!transports?.rest
    const sio = !!transports?.websocket

    const restPath = (transports?.rest as RestOptions)?.path
    const websocketOptions = (transports?.websocket as WebsocketOptions) || undefined
    const sioPath = websocketOptions?.path
    const sioConnectTimeout = websocketOptions?.connectTimeout
    const sioTransports = websocketOptions?.transports

    const defaultRestPath = JSON.stringify(restPath ?? '/')
    const defaultSioPath = JSON.stringify(sioPath ?? '/socket.io')
    const defaultSioConnectTimeout = JSON.stringify(sioConnectTimeout ?? 45000)
    const defaultSioTransports = JSON.stringify(sioTransports ?? ['websocket'])

    return `// ! Generated by nuxt-feathers-zod - do not change manually
import type { ClientApplication } from './client'
import { useRequestFetch } from '#app'
${puts([
  [sio, `import { io } from 'socket.io-client'`],
])}

export function connection(baseUrl: string, overrides?: { mode?: 'embedded' | 'remote', restPath?: string, websocketPath?: string, transport?: 'auto' | 'rest' | 'socketio' }) {
  return function (client: ClientApplication) {
    if (!baseUrl)
      throw new Error('[nuxt-feathers-zod] connection(): base url is required')

    const mode = overrides?.mode ?? 'embedded'
    const requestedTransport = overrides?.transport ?? 'auto'

    const base = new URL(baseUrl)
    const originOnly = base.origin
    const prefix = base.pathname === '/' ? '' : trimTrailingSlash(base.pathname)

    const DEFAULT_REST_PATH = ${defaultRestPath}
    const DEFAULT_SOCKET_PATH = ${defaultSioPath}
    const DEFAULT_SOCKET_CONNECT_TIMEOUT = ${defaultSioConnectTimeout}
    const DEFAULT_SOCKET_TRANSPORTS = ${defaultSioTransports}

    const restPathResolved = normalizePath(overrides?.restPath ?? (prefix || DEFAULT_REST_PATH))
    const websocketPathResolved = normalizePath(overrides?.websocketPath ?? (prefix ? joinPath(prefix, DEFAULT_SOCKET_PATH) : DEFAULT_SOCKET_PATH))
    const HAS_REST = ${rest ? 'true' : 'false'}
    const HAS_SOCKET = ${sio ? 'true' : 'false'}

${puts([
  [rest, `    const createRestConnection = () => {
      const finalBaseUrl = new URL(restPathResolved, originOnly).href
      const fetchImpl = resolveFetchImplementation(client)
      const restConnection = createNativeRestConnection(finalBaseUrl, fetchImpl)
      client.set('transport', 'rest')
      return restConnection
    }`],
  [sio, `    const createSocketConnection = () => {
      const socket = io(originOnly, {
        path: websocketPathResolved,
        connectTimeout: DEFAULT_SOCKET_CONNECT_TIMEOUT,
        transports: DEFAULT_SOCKET_TRANSPORTS,
      })
      const socketConnection = createNativeSocketioConnection(socket)
      client.set('socket', socket)
      client.set('transport', 'socketio')
      return socketConnection
    }`],
])}

    function resolveTransport() {
      if (requestedTransport === 'rest')
        return HAS_REST ? 'rest' : (HAS_SOCKET ? 'socketio' : 'rest')

      if (requestedTransport === 'socketio')
        return HAS_SOCKET ? 'socketio' : (HAS_REST ? 'rest' : 'socketio')

      if (mode === 'remote')
        return HAS_SOCKET ? 'socketio' : 'rest'

      return HAS_REST ? 'rest' : 'socketio'
    }

    const transport = resolveTransport()

    let configured: any
    if (transport === 'rest') {
      configured = ${put(rest, 'createRestConnection()', 'undefined as any')}
    }
    else if (transport === 'socketio') {
      configured = ${put(sio, 'createSocketConnection()', put(rest, 'createRestConnection()', 'undefined as any'))}
    }
    else {
      configured = ${put(rest, 'createRestConnection()', put(sio, 'createSocketConnection()', 'undefined as any'))}
    }

    client.set('connection', configured)
    ;(client as any).setDefaultService?.((path: string) => configured.service(path))
  }
}

${put(rest, `function createNativeRestConnection(baseUrl: string, fetchImpl: NativeFetch) {
  return {
    service(path: string) {
      return createNativeRestService(baseUrl, path, fetchImpl)
    },
  }
}

type NativeFetch = (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>

function createNativeRestService(baseUrl: string, servicePath: string, fetchImpl: NativeFetch) {
  const base = trimTrailingSlash(baseUrl)
  const path = normalizePath(servicePath)
  const serviceUrl = new URL(path.replace(/^\\//, ''), base.endsWith('/') ? base : base + '/')

  const request = async (method: string, id: any, data?: any, params?: any) => {
    const url = new URL(id === null || typeof id === 'undefined' ? serviceUrl.href : joinPath(serviceUrl.href, encodeURIComponent(String(id))))
    appendQuery(url, params?.query)

    const headers = new Headers(params?.headers || params?.connection?.headers || {})
    headers.set('Accept', 'application/json')

    const init: RequestInit = {
      ...(params?.connection || {}),
      method,
      headers,
    }

    if (typeof data !== 'undefined') {
      headers.set('Content-Type', 'application/json')
      init.body = JSON.stringify(data)
    }

    const response = await fetchImpl(url, init)
    return await parseResponse(response)
  }

  return withServiceEvents({
    find(params?: any) { return request('GET', null, undefined, params) },
    get(id: any, params?: any) { return request('GET', id, undefined, params) },
    create(data: any, params?: any) { return request('POST', null, data, params) },
    update(id: any, data: any, params?: any) { return request('PUT', id, data, params) },
    patch(id: any, data: any, params?: any) { return request('PATCH', id, data, params) },
    remove(id: any, params?: any) { return request('DELETE', id, undefined, params) },
  })
}
`, '')}
${put(sio, `function createNativeSocketioConnection(socket: any) {
  return {
    service(path: string) {
      return createNativeSocketioService(socket, path)
    },
  }
}

function createNativeSocketioService(socket: any, path: string) {
  const emit = (method: string, ...args: any[]) => new Promise((resolve, reject) => {
    socket.emit(method, path, ...args, (error: any, result: any) => {
      if (error) reject(error)
      else resolve(result)
    })
  })

  return withServiceEvents({
    find(params?: any) { return emit('find', params) },
    get(id: any, params?: any) { return emit('get', id, params) },
    create(data: any, params?: any) { return emit('create', data, params) },
    update(id: any, data: any, params?: any) { return emit('update', id, data, params) },
    patch(id: any, data: any, params?: any) { return emit('patch', id, data, params) },
    remove(id: any, params?: any) { return emit('remove', id, params) },
  }, socket, path)
}
`, '')}
function resolveFetchImplementation(client: ClientApplication) {
  const nativeFetch: NativeFetch = import.meta.server
    ? (useRequestFetch() as unknown as NativeFetch)
    : (typeof window !== 'undefined' && typeof window.fetch === 'function'
        ? window.fetch.bind(window)
        : globalThis.fetch.bind(globalThis))

  return async function nfzFetch(input: RequestInfo | URL, init: RequestInit = {}) {
    const headers = new Headers(init.headers || {})
    const token = await (client as any).authentication?.getAccessToken?.()
    if (token && !headers.has('authorization') && !headers.has('Authorization'))
      headers.set('Authorization', \`Bearer \${token}\`)

    return await nativeFetch(input, { ...init, headers })
  }
}

async function parseResponse(response: Response) {
  if (response.status === 204)
    return null

  const contentType = response.headers.get('content-type') || ''
  const payload = contentType.includes('application/json')
    ? await response.json().catch(() => null)
    : await response.text().catch(() => null)

  if (!response.ok) {
    const message = payload?.message || response.statusText || 'Request failed'
    throw Object.assign(new Error(message), {
      name: payload?.name || 'NfzRestClientError',
      code: payload?.code,
      className: payload?.className,
      status: response.status,
      statusCode: response.status,
      data: payload,
    })
  }

  return payload
}

function appendQuery(url: URL, query: Record<string, any> | undefined) {
  if (!query || typeof query !== 'object') return
  for (const [key, value] of Object.entries(query)) {
    if (typeof value === 'undefined') continue
    if (Array.isArray(value)) {
      for (const item of value)
        url.searchParams.append(key, serializeQueryValue(item))
    }
    else {
      url.searchParams.set(key, serializeQueryValue(value))
    }
  }
}

function serializeQueryValue(value: any) {
  if (value === null) return 'null'
  if (typeof value === 'object') return JSON.stringify(value)
  return String(value)
}

function withServiceEvents(service: any, socket?: any, path?: string) {
  const listeners = new Map<string, Set<Function>>()
  service.on = (event: string, listener: Function) => {
    const set = listeners.get(event) || new Set<Function>()
    set.add(listener)
    listeners.set(event, set)
    if (socket && path) socket.on(\`\${path} \${event}\`, listener)
    return service
  }
  service.off = (event: string, listener?: Function) => {
    if (!listener) listeners.delete(event)
    else listeners.get(event)?.delete(listener)
    if (socket && path && listener) socket.off?.(\`\${path} \${event}\`, listener)
    return service
  }
  service.emit = (event: string, ...args: any[]) => {
    const set = listeners.get(event)
    if (!set?.size) return false
    for (const listener of set) listener(...args)
    return true
  }
  return service
}

function trimTrailingSlash(value: string) {
  let s = value
  while (s.length > 1 && s.endsWith('/')) s = s.slice(0, -1)
  return s
}
function ensureLeadingSlash(value: string) {
  if (!value) return '/'
  return value.startsWith('/') ? value : '/' + value
}
function normalizePath(value: string) {
  const s = ensureLeadingSlash(value)
  return s === '/' ? s : trimTrailingSlash(s)
}
function joinPath(a: string, b: string) {
  const left = a === '/' ? '' : trimTrailingSlash(a)
  const right = ensureLeadingSlash(b)
  return left + right
}
`
  }
}
