import type { Resolver } from '@nuxt/kit'
import type { ResolvedOptions } from '../../options'
import type { ClientOptions } from '../../options/client'
import type { RestOptions } from '../../options/transports/rest'
import type { WebsocketOptions } from '../../options/transports/websocket'
import { put, puts } from '../utils'

export function getClientConnectionContents(options: ResolvedOptions, resolver: Resolver) {
  return (): string => {
    const transports = options?.transports
    const rest = !!transports?.rest
    const sio = !!transports?.websocket

    const restPath = (transports?.rest as RestOptions)?.path
    const websocketOptions = (transports?.websocket as WebsocketOptions) || undefined
    const sioPath = websocketOptions?.path
    const sioConnectTimeout = websocketOptions?.connectTimeout
    const sioTransports = websocketOptions?.transports

    const defaultRestPath = JSON.stringify(restPath ?? '/')
    const defaultSioPath = JSON.stringify(sioPath ?? '/socket.io')
    const defaultSioConnectTimeout = JSON.stringify(sioConnectTimeout ?? 45000)
    const defaultSioTransports = JSON.stringify(sioTransports ?? ['websocket'])

    return `// ! Generated by nuxt-feathers-zod - do not change manually
import type { ClientApplication } from './client'
import { useAuthBoundFetchImplementation } from 'nuxt-feathers-zod/auth-bound-fetch'
${puts([
  [rest, `import rest from '@feathersjs/rest-client'`],
  [sio, `import socketioClient from '@feathersjs/socketio-client'
import { io } from 'socket.io-client'`],
])}

export function connection(baseUrl: string, overrides?: { mode?: 'embedded' | 'remote', restPath?: string, websocketPath?: string, transport?: 'auto' | 'rest' | 'socketio' }) {
  return function (client: ClientApplication) {
    if (!baseUrl)
      throw new Error('[nuxt-feathers-zod] connection(): base url is required')

    const mode = overrides?.mode ?? 'embedded'
    const requestedTransport = overrides?.transport ?? 'auto'

    const base = new URL(baseUrl)
    const originOnly = base.origin
    const prefix = base.pathname === '/' ? '' : trimTrailingSlash(base.pathname)

    const DEFAULT_REST_PATH = ${defaultRestPath}
    const DEFAULT_SOCKET_PATH = ${defaultSioPath}
    const DEFAULT_SOCKET_CONNECT_TIMEOUT = ${defaultSioConnectTimeout}
    const DEFAULT_SOCKET_TRANSPORTS = ${defaultSioTransports}

    const restPathResolved = normalizePath(overrides?.restPath ?? (prefix || DEFAULT_REST_PATH))
    const websocketPathResolved = normalizePath(overrides?.websocketPath ?? (prefix ? joinPath(prefix, DEFAULT_SOCKET_PATH) : DEFAULT_SOCKET_PATH))
    const HAS_REST = ${rest ? 'true' : 'false'}
    const HAS_SOCKET = ${sio ? 'true' : 'false'}

${puts([
  [rest, `    const createRestConnection = () => {
      const finalBaseUrl = new URL(restPathResolved, originOnly).href
      const restClient = rest(finalBaseUrl)
      const fetchImpl = resolveFetchImplementation()
      client.set('transport', 'rest')
      return restClient.fetch(fetchImpl)
    }`],
  [sio, `    const createSocketConnection = () => {
      const socket = io(originOnly, {
        path: websocketPathResolved,
        connectTimeout: DEFAULT_SOCKET_CONNECT_TIMEOUT,
        transports: DEFAULT_SOCKET_TRANSPORTS,
      })
      client.set('socket', socket)
      client.set('transport', 'socketio')
      return socketioClient(socket)
    }`],
])}

    function resolveTransport() {
      if (requestedTransport === 'rest')
        return HAS_REST ? 'rest' : (HAS_SOCKET ? 'socketio' : 'rest')

      if (requestedTransport === 'socketio')
        return HAS_SOCKET ? 'socketio' : (HAS_REST ? 'rest' : 'socketio')

      if (mode === 'remote')
        return HAS_SOCKET ? 'socketio' : 'rest'

      return HAS_REST ? 'rest' : 'socketio'
    }

    const transport = resolveTransport()

    let configured: any
    if (transport === 'rest') {
      configured = ${put(rest, 'createRestConnection()', 'undefined as any')}
    }
    else if (transport === 'socketio') {
      configured = ${put(sio, 'createSocketConnection()', put(rest, 'createRestConnection()', 'undefined as any'))}
    }
    else {
      configured = ${put(rest, 'createRestConnection()', put(sio, 'createSocketConnection()', 'undefined as any'))}
    }

    client.configure(configured)
    client.set('connection', configured)
  }
}

function resolveFetchImplementation() {
  return useAuthBoundFetchImplementation({ auth: 'required', retryOn401: true })
}

function trimTrailingSlash(value: string) {
  let s = value
  while (s.length > 1 && s.endsWith('/')) s = s.slice(0, -1)
  return s
}
function ensureLeadingSlash(value: string) {
  if (!value) return '/'
  return value.startsWith('/') ? value : '/' + value
}
function normalizePath(value: string) {
  const s = ensureLeadingSlash(value)
  return s === '/' ? s : trimTrailingSlash(s)
}
function joinPath(a: string, b: string) {
  const left = a === '/' ? '' : trimTrailingSlash(a)
  const right = ensureLeadingSlash(b)
  return left + right
}
`
  }
}
