import type { Import } from 'unimport'
import type { ResolvedOptions } from '../../options'
import type { DefaultAuthOptions } from '../../options/authentication'
import type { ClientOptions, ResolvedClientOptions } from '../../options/client'
import type { ServicesDirs } from '../../options/services'
import { scanDirExports } from 'unimport'
import { setImportsMeta } from '../../options/utils'
import { put } from '../utils'

async function getServices(servicesDirs: ServicesDirs): Promise<Import[]> {
  const services = await scanDirExports(servicesDirs, {
    filePatterns: ['**/*.shared.ts'],
    fileFilter: file => /\.shared\.ts$/.test(file),
    types: false,
  })
  return services.filter(({ name }) => /Client|default$/.test(name))
}

export function getClientPluginContents(options: ResolvedOptions) {
  return async (): Promise<string> => {
    // In remote mode, the client talks to an external Feathers backend.
    // We must NOT auto-import local generated "*.shared" service clients, because:
    // - they are unnecessary (services are external)
    // - they can introduce build-time coupling and TS issues in consumer apps
    // Embedded mode keeps the legacy behavior (scan + configure).
    const resolvedMode = (options.client as ResolvedClientOptions)?.mode
    const services = resolvedMode === 'remote'
      ? []
      : setImportsMeta(await getServices(options.servicesDirs))

    const plugins = (options.client as ResolvedClientOptions).plugins

    const modules = [...services, ...plugins]

    const moduleAuth = ((options?.auth as DefaultAuthOptions)?.authStrategies || []).length > 0
    const remoteAuthEnabled = Boolean((options?.client as ResolvedClientOptions)?.remote?.auth?.enabled)
    const auth = moduleAuth || remoteAuthEnabled
    const pinia = !!(options?.client as ClientOptions)?.pinia

    return `// ! Generated by nuxt-feathers-zod - do not change manually
// For more information about this file see https://dove.feathersjs.com/guides/cli/client.html

import { useCookie, useRequestURL } from "#imports"
import type { ClientApplication } from './client'
import { feathers } from '@feathersjs/feathers'
import { defineNuxtPlugin, useRuntimeConfig } from '#app'
import { buildRemoteAuthPayload } from 'nuxt-feathers-zod/auth-utils'
import { getPublicClientMode, getPublicRemoteAuthConfig, getPublicRemoteConfig } from 'nuxt-feathers-zod/config-utils'
${put(pinia, `import { createPiniaClient, type CreatePiniaClientConfig } from 'feathers-pinia'`)}

import { connection } from './connection'
${put(auth, `import { authentication } from './authentication'`)}

${modules.map(module => module.meta.import).join('\n')}

/**
 * Returns a typed client for the feathers-api app.
 *
 * @param connection The REST or Socket.io Feathers client connection
 * @param authenticationOptions Additional settings for the authentication client
 * @see https://dove.feathersjs.com/api/client.html
 * @returns The Feathers client application
 */
function createFeathersClient(): ClientApplication {
  const feathersClient: ClientApplication = feathers()

  // Init connection
  const { origin } = useRequestURL()
  const runtime = useRuntimeConfig()
  const clientMode = getPublicClientMode(runtime.public as any)
  const remoteConfig = getPublicRemoteConfig(runtime.public as any)
  const remoteUrl = remoteConfig?.url
  const remoteRestPath = remoteConfig?.restPath
  const remoteWebsocketPath = remoteConfig?.websocketPath
  const remoteTransport = remoteConfig?.transport
  const remoteAuth = getPublicRemoteAuthConfig(runtime.public as any)
  const remoteServices = remoteConfig?.services
  const baseUrl = clientMode === 'remote' && remoteUrl ? remoteUrl : origin
  const overrides = clientMode === 'remote'
    ? { restPath: remoteRestPath, websocketPath: remoteWebsocketPath, transport: remoteTransport }
    : undefined
  feathersClient.configure(connection(baseUrl, overrides))

  // DX/runtime safety: normalize "weird" rejections (e.g. Promise.reject() with no reason)
  // so downstream tooling (feathers-pinia) never crashes when mapping errors.
  const normalizeError = (err: any) => {
    // feathers-pinia expects an object with a stable 'code' field.
    // In practice, some transports or userland code may reject with:
    // - 'undefined' / 'null'
    // - a primitive (string/number)
    // - an object that has 'code' but it's empty/undefined
    // Normalize all of those cases so downstream mapping never crashes.

    if (err == null) {
      const e: any = new Error('Unknown error')
      e.code = 'NFZ_UNKNOWN'
      return e
    }

    if (typeof err !== 'object') {
      const e: any = new Error(String(err))
      e.code = 'NFZ_ERROR'
      return e
    }

    const anyErr: any = err
    // ofetch/undici errors generally expose status/statusCode
    const fallbackCode = anyErr.statusCode ?? anyErr.status ?? anyErr.name ?? 'ERROR'
    if (!('code' in anyErr) || anyErr.code == null || anyErr.code === '')
      anyErr.code = fallbackCode

    return anyErr
  }

  // Wrap services lazily to guarantee consistent error shapes
  const _service = (feathersClient as any).service?.bind(feathersClient)
  if (typeof _service === 'function') {
    ;(feathersClient as any).service = (path: any) => {
      const svc = _service(path)
      if (!svc || typeof svc !== 'object' || (svc as any).__nfz_wrapped)
        return svc

      const wrap = (method: string) => {
        const fn = (svc as any)[method]
        if (typeof fn !== 'function') return
        ;(svc as any)[method] = async (...args: any[]) => {
          try {
            return await fn.apply(svc, args)
          }
          catch (e: any) {
            throw normalizeError(e)
          }
        }
      }

      for (const m of ['find', 'get', 'create', 'update', 'patch', 'remove'])
        wrap(m)

      ;(svc as any).__nfz_wrapped = true
      return svc
    }
  }

  // Init authentication
  ${put(auth, `feathersClient.configure(authentication)`)}

  // Init remote services (manifest not required)
  if (clientMode === 'remote' && Array.isArray(remoteServices) && remoteServices.length) {
    const conn: any = (feathersClient as any).get?.('connection')
    for (const svc of remoteServices) {
      const path = String((svc as any)?.path || '').trim()
      if (!path) continue
      const methods = Array.isArray((svc as any).methods) ? (svc as any).methods : undefined
      try {
        const remote = conn?.service ? conn.service(path) : undefined
        if (remote) {
          ;(feathersClient as any).use(path, remote, { methods: methods || ['find','get','create','update','patch','remove'] })
        }
      } catch (e) {
        // ignore
      }
    }
  }

  // Init services
  ${services.map(service => `feathersClient.configure(${service.meta.importId})`).join('\n  ')}

  // Init plugins
  ${plugins.map(plugin => `feathersClient.configure(${plugin.meta.importId})`).join('\n  ')}

  return feathersClient
}

/**
 * Creates a Feathers Rest client for the SSR server and a Socket.io client for the browser.
 * Also provides a cookie-storage adapter for JWT SSR using Nuxt APIs.
 */
export default defineNuxtPlugin(async (nuxt) => {
  // create the feathers client
  const feathersClient: ClientApplication = createFeathersClient()

  // Remote auth: normalize startup + Socket.IO reconnect behavior.
  const rc = useRuntimeConfig() as any
  const cm = getPublicClientMode(rc.public as any)
  const ra = getPublicRemoteAuthConfig(rc.public as any)

  async function resolveRemoteToken() {
    if (import.meta.server)
      return null

    const keycloak = (nuxt as any).$keycloak
    if (ra?.payloadMode === 'keycloak' && keycloak?.authenticated) {
      try {
        await keycloak.updateToken?.(30)
      }
      catch {}
      const kcToken = typeof keycloak?.token === 'function' ? keycloak.token() : keycloak?.token
      if (typeof kcToken === 'string' && kcToken)
        return kcToken
    }

    const storageKey = ra?.storageKey || rc.public?._feathers?.auth?.client?.storageKey || 'feathers-jwt'
    const jwt = useCookie<string | null>(storageKey)
    return jwt.value || null
  }

  async function remoteAuthenticate(reason: string) {
    if (import.meta.server || cm !== 'remote' || !ra?.enabled)
      return

    const api: any = feathersClient as any
    const token = await resolveRemoteToken()

    try {
      if (token) {
        const payload = buildRemoteAuthPayload(token, ra)
        await api.authenticate?.(payload)
        return
      }

      if (ra?.reauth !== false)
        await api.reAuthenticate?.()
    }
    catch (e) {
      // ignore startup/reconnect auth errors
    }
  }

  if (import.meta.client && cm === 'remote' && ra?.enabled) {
    await remoteAuthenticate('startup')

    const socket = (feathersClient as any).get?.('socket')
    if (socket?.on) {
      socket.on('connect', () => {
        void remoteAuthenticate('socket-connect')
      })
      socket.on('reconnect', () => {
        void remoteAuthenticate('socket-reconnect')
      })
    }
  }
  ${put(pinia, `
  const piniaOptions = useRuntimeConfig().public._feathers.pinia
  `)}
  // wrap the feathers client (Pinia optional)
  const piniaClient = ${put(pinia, `createPiniaClient(feathersClient, {
    ssr: !!import.meta.server,
    ...piniaOptions as CreatePiniaClientConfig,
    pinia: nuxt.$pinia,
  })`, `undefined`)}

  // $api is always the real Feathers client (transport-aware).
  // This avoids confusion in remote mode where a Pinia-wrapped client may not expose transport internals.
  const api = feathersClient

  // Extra DX safety (remote or embedded): make sure errors never crash feathers-pinia internals
  // when a transport rejects with an unexpected reason (undefined/null/primitive).
  const normalizeError = (err: any) => {
    if (err == null) {
      const e: any = new Error('Unknown error')
      e.code = 'NFZ_UNKNOWN'
      return e
    }
    if (typeof err !== 'object') {
      const e: any = new Error(String(err))
      e.code = 'NFZ_ERROR'
      return e
    }
    const anyErr: any = err
    const fallbackCode = anyErr.statusCode ?? anyErr.status ?? anyErr.name ?? 'ERROR'
    if (!('code' in anyErr) || anyErr.code == null || anyErr.code === '')
      anyErr.code = fallbackCode
    return anyErr
  }

  // If we're using feathers-pinia, also wrap api.service() methods to ensure the same safety.
  if (api && typeof (api as any).service === 'function') {
    const _apiService = (api as any).service.bind(api)
    ;(api as any).service = (path: any) => {
      const svc = _apiService(path)
      if (!svc || typeof svc !== 'object' || (svc as any).__nfz_api_wrapped)
        return svc

      const wrap = (method: string) => {
        const fn = (svc as any)[method]
        if (typeof fn !== 'function') return
        ;(svc as any)[method] = async (...args: any[]) => {
          try {
            return await fn.apply(svc, args)
          }
          catch (e: any) {
            throw normalizeError(e)
          }
        }
      }

      for (const m of ['find', 'get', 'create', 'update', 'patch', 'remove'])
        wrap(m)

      ;(svc as any).__nfz_api_wrapped = true
      return svc
    }
  }

  return {
    provide: {
      api,
      client: feathersClient,
      feathersClient,
      piniaClient,
    },
  }
})
`
  }
}
