import type { ResolvedOptions } from '../../options'
import type { DefaultAuthOptions } from '../../options/authentication'
import type { ClientOptions, ResolvedClientOptions } from '../../options/client'

import { discoverClientServices } from '../../discovery'
import { setImportsMeta } from '../../options/utils'

export function getClientPluginContents(options: ResolvedOptions) {
  return async (): Promise<string> => {
    const resolvedMode = (options.client as ResolvedClientOptions)?.mode
    const services = resolvedMode === 'remote'
      ? []
      : setImportsMeta(await discoverClientServices(options.servicesDirs))

    const plugins = (options.client as ResolvedClientOptions).plugins
    const modules = [...services, ...plugins]

    const moduleAuth = ((options.auth as DefaultAuthOptions)?.authStrategies || []).length > 0
    const remoteAuthEnabled = Boolean((options.client as ResolvedClientOptions)?.remote?.auth?.enabled)
    const authEnabled = moduleAuth || remoteAuthEnabled
    const piniaEnabled = Boolean((options.client as ClientOptions)?.pinia)
    const remoteServices = (options.client as ResolvedClientOptions)?.remote?.services || []

    return `// ! Generated by nuxt-feathers-zod - do not change manually
import { defineNfzClientPlugin } from 'nuxt-feathers-zod/client-runtime'
${modules.map(module => module.meta.import).join('\n')}

const nfzClientPluginConfig = {
  authEnabled: ${JSON.stringify(authEnabled)},
  piniaEnabled: ${JSON.stringify(piniaEnabled)},
  remoteServices: ${JSON.stringify(remoteServices, null, 2)},
  services: [
    ${services.map(service => service.meta.importId).join(',\n    ')}
  ],
  plugins: [
    ${plugins.map(plugin => plugin.meta.importId).join(',\n    ')}
  ],
  debug: ${JSON.stringify(true)},
} as const

export default defineNfzClientPlugin(nfzClientPluginConfig)
`
  }
}
