import type { ModuleOptions as PiniaNuxtModuleOptions } from '@pinia/nuxt'
import { klona } from 'klona'

export type PiniaModuleOptions = Pick<PiniaNuxtModuleOptions, 'storesDirs'>

export interface PiniaSessionOptions {
  /** Redirect target used by the built-in named route middleware `session`. */
  redirectTo?: string
  /** Public routes ignored by the built-in named route middleware `session`. */
  publicRoutes?: string[]
}

export interface PiniaOptions extends PiniaModuleOptions {
  /** Legacy compatibility only. Raw Feathers client calls do not use this value. */
  idField?: string
  /** Legacy compatibility only. Service cache stores are no longer generated by NFZ. */
  services?: Record<string, Record<string, unknown>>
  /** Options consumed by the built-in session middleware. */
  session?: PiniaSessionOptions
}

export type ResolvedPiniaOptions = Required<Pick<PiniaOptions, 'storesDirs' | 'idField'>> & Omit<PiniaOptions, 'storesDirs' | 'idField'>

export type ResolvedPiniaOptionsOrDisabled = ResolvedPiniaOptions | false

export const piniaDefaults: ResolvedPiniaOptions = {
  storesDirs: ['stores'],
  idField: 'id',
  session: {
    redirectTo: '/login',
    publicRoutes: ['/', '/login', '/auth/login', '/auth/callback', '/silent-check-sso.html'],
  },
}

export function getPiniaDefaults(mongodb: boolean): ResolvedPiniaOptions {
  const resolvedPiniaDefaults: ResolvedPiniaOptions = klona(piniaDefaults)
  if (mongodb)
    resolvedPiniaDefaults.idField = '_id'
  return resolvedPiniaDefaults
}

export function resolvePiniaOptions(piniaOptions: PiniaOptions | boolean | undefined, mongodb: boolean): ResolvedPiniaOptionsOrDisabled {
  const piniaDefaultOptions = getPiniaDefaults(mongodb)

  // Pinia is now the standard application/session-store layer.
  // `false` remains supported for applications that do not want @pinia/nuxt.
  if (piniaOptions === false)
    return false

  if (piniaOptions === true || piniaOptions === undefined)
    return piniaDefaultOptions

  return {
    ...piniaDefaultOptions,
    ...piniaOptions,
    session: {
      ...(piniaDefaultOptions.session || {}),
      ...(piniaOptions.session || {}),
    },
  }
}
